/*
Payments API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ListConnectorTasks200Response struct for ListConnectorTasks200Response
type ListConnectorTasks200Response struct {
	Cursor *Cursor     `json:"cursor,omitempty"`
	Data   interface{} `json:"data,omitempty"`
}

// NewListConnectorTasks200Response instantiates a new ListConnectorTasks200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListConnectorTasks200Response() *ListConnectorTasks200Response {
	this := ListConnectorTasks200Response{}
	return &this
}

// NewListConnectorTasks200ResponseWithDefaults instantiates a new ListConnectorTasks200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListConnectorTasks200ResponseWithDefaults() *ListConnectorTasks200Response {
	this := ListConnectorTasks200Response{}
	return &this
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *ListConnectorTasks200Response) GetCursor() Cursor {
	if o == nil || isNil(o.Cursor) {
		var ret Cursor
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListConnectorTasks200Response) GetCursorOk() (*Cursor, bool) {
	if o == nil || isNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *ListConnectorTasks200Response) HasCursor() bool {
	if o != nil && !isNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given Cursor and assigns it to the Cursor field.
func (o *ListConnectorTasks200Response) SetCursor(v Cursor) {
	o.Cursor = &v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListConnectorTasks200Response) GetData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListConnectorTasks200Response) GetDataOk() (*interface{}, bool) {
	if o == nil || isNil(o.Data) {
		return nil, false
	}
	return &o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListConnectorTasks200Response) HasData() bool {
	if o != nil && isNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given interface{} and assigns it to the Data field.
func (o *ListConnectorTasks200Response) SetData(v interface{}) {
	o.Data = v
}

func (o ListConnectorTasks200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableListConnectorTasks200Response struct {
	value *ListConnectorTasks200Response
	isSet bool
}

func (v NullableListConnectorTasks200Response) Get() *ListConnectorTasks200Response {
	return v.value
}

func (v *NullableListConnectorTasks200Response) Set(val *ListConnectorTasks200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListConnectorTasks200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListConnectorTasks200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListConnectorTasks200Response(val *ListConnectorTasks200Response) *NullableListConnectorTasks200Response {
	return &NullableListConnectorTasks200Response{value: val, isSet: true}
}

func (v NullableListConnectorTasks200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListConnectorTasks200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
