/*
Payments API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// CursorTotal struct for CursorTotal
type CursorTotal struct {
	// The total number of items available
	Value interface{} `json:"value,omitempty"`
}

// NewCursorTotal instantiates a new CursorTotal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCursorTotal() *CursorTotal {
	this := CursorTotal{}
	return &this
}

// NewCursorTotalWithDefaults instantiates a new CursorTotal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCursorTotalWithDefaults() *CursorTotal {
	this := CursorTotal{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CursorTotal) GetValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CursorTotal) GetValueOk() (*interface{}, bool) {
	if o == nil || isNil(o.Value) {
		return nil, false
	}
	return &o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CursorTotal) HasValue() bool {
	if o != nil && isNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given interface{} and assigns it to the Value field.
func (o *CursorTotal) SetValue(v interface{}) {
	o.Value = v
}

func (o CursorTotal) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableCursorTotal struct {
	value *CursorTotal
	isSet bool
}

func (v NullableCursorTotal) Get() *CursorTotal {
	return v.value
}

func (v *NullableCursorTotal) Set(val *CursorTotal) {
	v.value = val
	v.isSet = true
}

func (v NullableCursorTotal) IsSet() bool {
	return v.isSet
}

func (v *NullableCursorTotal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCursorTotal(val *CursorTotal) *NullableCursorTotal {
	return &NullableCursorTotal{value: val, isSet: true}
}

func (v NullableCursorTotal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCursorTotal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
