/*
Payments API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// GetPayment200Response struct for GetPayment200Response
type GetPayment200Response struct {
	Data *Payment `json:"data,omitempty"`
}

// NewGetPayment200Response instantiates a new GetPayment200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPayment200Response() *GetPayment200Response {
	this := GetPayment200Response{}
	return &this
}

// NewGetPayment200ResponseWithDefaults instantiates a new GetPayment200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPayment200ResponseWithDefaults() *GetPayment200Response {
	this := GetPayment200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetPayment200Response) GetData() Payment {
	if o == nil || isNil(o.Data) {
		var ret Payment
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPayment200Response) GetDataOk() (*Payment, bool) {
	if o == nil || isNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetPayment200Response) HasData() bool {
	if o != nil && !isNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given Payment and assigns it to the Data field.
func (o *GetPayment200Response) SetData(v Payment) {
	o.Data = &v
}

func (o GetPayment200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetPayment200Response struct {
	value *GetPayment200Response
	isSet bool
}

func (v NullableGetPayment200Response) Get() *GetPayment200Response {
	return v.value
}

func (v *NullableGetPayment200Response) Set(val *GetPayment200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPayment200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPayment200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPayment200Response(val *GetPayment200Response) *NullableGetPayment200Response {
	return &NullableGetPayment200Response{value: val, isSet: true}
}

func (v NullableGetPayment200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPayment200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
