/*
Payments API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ReadConnectorConfig200Response struct for ReadConnectorConfig200Response
type ReadConnectorConfig200Response struct {
	Data interface{} `json:"data,omitempty"`
}

// NewReadConnectorConfig200Response instantiates a new ReadConnectorConfig200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReadConnectorConfig200Response() *ReadConnectorConfig200Response {
	this := ReadConnectorConfig200Response{}
	return &this
}

// NewReadConnectorConfig200ResponseWithDefaults instantiates a new ReadConnectorConfig200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReadConnectorConfig200ResponseWithDefaults() *ReadConnectorConfig200Response {
	this := ReadConnectorConfig200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReadConnectorConfig200Response) GetData() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReadConnectorConfig200Response) GetDataOk() (*interface{}, bool) {
	if o == nil || isNil(o.Data) {
		return nil, false
	}
	return &o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ReadConnectorConfig200Response) HasData() bool {
	if o != nil && isNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given interface{} and assigns it to the Data field.
func (o *ReadConnectorConfig200Response) SetData(v interface{}) {
	o.Data = v
}

func (o ReadConnectorConfig200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableReadConnectorConfig200Response struct {
	value *ReadConnectorConfig200Response
	isSet bool
}

func (v NullableReadConnectorConfig200Response) Get() *ReadConnectorConfig200Response {
	return v.value
}

func (v *NullableReadConnectorConfig200Response) Set(val *ReadConnectorConfig200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableReadConnectorConfig200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableReadConnectorConfig200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReadConnectorConfig200Response(val *ReadConnectorConfig200Response) *NullableReadConnectorConfig200Response {
	return &NullableReadConnectorConfig200Response{value: val, isSet: true}
}

func (v NullableReadConnectorConfig200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReadConnectorConfig200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
