/*
Payments API

Testing PaymentsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	"testing"

	openapiclient "github.com/formancehq/payments/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_client_PaymentsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PaymentsApiService GetAllConnectors", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.PaymentsApi.GetAllConnectors(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentsApiService GetAllConnectorsConfigs", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.PaymentsApi.GetAllConnectorsConfigs(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentsApiService GetConnectorTask", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var connector interface{}
		var taskId interface{}

		resp, httpRes, err := apiClient.PaymentsApi.GetConnectorTask(context.Background(), connector, taskId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentsApiService GetPayment", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var paymentId interface{}

		resp, httpRes, err := apiClient.PaymentsApi.GetPayment(context.Background(), paymentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentsApiService InstallConnector", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var connector interface{}

		httpRes, err := apiClient.PaymentsApi.InstallConnector(context.Background(), connector).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentsApiService ListConnectorTasks", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var connector interface{}

		resp, httpRes, err := apiClient.PaymentsApi.ListConnectorTasks(context.Background(), connector).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentsApiService ListPayments", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.PaymentsApi.ListPayments(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentsApiService ReadConnectorConfig", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var connector interface{}

		resp, httpRes, err := apiClient.PaymentsApi.ReadConnectorConfig(context.Background(), connector).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentsApiService ResetConnector", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var connector interface{}

		httpRes, err := apiClient.PaymentsApi.ResetConnector(context.Background(), connector).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentsApiService UninstallConnector", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var connector interface{}

		httpRes, err := apiClient.PaymentsApi.UninstallConnector(context.Background(), connector).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
