// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source client.go -destination client_generated.go -package client . Client
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetAssets mocks base method.
func (m *MockClient) GetAssets(ctx context.Context, entityID string) (*AssetsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssets", ctx, entityID)
	ret0, _ := ret[0].(*AssetsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssets indicates an expected call of GetAssets.
func (mr *MockClientMockRecorder) GetAssets(ctx, entityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssets", reflect.TypeOf((*MockClient)(nil).GetAssets), ctx, entityID)
}

// GetBalanceForWallet mocks base method.
func (m *MockClient) GetBalanceForWallet(ctx context.Context, walletID string) (*WalletBalanceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceForWallet", ctx, walletID)
	ret0, _ := ret[0].(*WalletBalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceForWallet indicates an expected call of GetBalanceForWallet.
func (mr *MockClientMockRecorder) GetBalanceForWallet(ctx, walletID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceForWallet", reflect.TypeOf((*MockClient)(nil).GetBalanceForWallet), ctx, walletID)
}

// GetPortfolio mocks base method.
func (m *MockClient) GetPortfolio(ctx context.Context) (*PortfolioResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPortfolio", ctx)
	ret0, _ := ret[0].(*PortfolioResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPortfolio indicates an expected call of GetPortfolio.
func (mr *MockClientMockRecorder) GetPortfolio(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPortfolio", reflect.TypeOf((*MockClient)(nil).GetPortfolio), ctx)
}

// GetTransactions mocks base method.
func (m *MockClient) GetTransactions(ctx context.Context, cursor string, pageSize int, types ...string) (*TransactionsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, cursor, pageSize}
	for _, a := range types {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTransactions", varargs...)
	ret0, _ := ret[0].(*TransactionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactions indicates an expected call of GetTransactions.
func (mr *MockClientMockRecorder) GetTransactions(ctx, cursor, pageSize any, types ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, cursor, pageSize}, types...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactions", reflect.TypeOf((*MockClient)(nil).GetTransactions), varargs...)
}

// GetWallets mocks base method.
func (m *MockClient) GetWallets(ctx context.Context, cursor string, pageSize int) (*WalletsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWallets", ctx, cursor, pageSize)
	ret0, _ := ret[0].(*WalletsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWallets indicates an expected call of GetWallets.
func (mr *MockClientMockRecorder) GetWallets(ctx, cursor, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWallets", reflect.TypeOf((*MockClient)(nil).GetWallets), ctx, cursor, pageSize)
}

// ListOrders mocks base method.
func (m *MockClient) ListOrders(ctx context.Context, cursor string, pageSize int) (*OrdersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrders", ctx, cursor, pageSize)
	ret0, _ := ret[0].(*OrdersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrders indicates an expected call of ListOrders.
func (mr *MockClientMockRecorder) ListOrders(ctx, cursor, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrders", reflect.TypeOf((*MockClient)(nil).ListOrders), ctx, cursor, pageSize)
}
