// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source client.go -destination client_generated.go -package client . Client
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetAssetPairs mocks base method.
func (m *MockClient) GetAssetPairs(ctx context.Context) (map[string]AssetPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssetPairs", ctx)
	ret0, _ := ret[0].(map[string]AssetPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssetPairs indicates an expected call of GetAssetPairs.
func (mr *MockClientMockRecorder) GetAssetPairs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssetPairs", reflect.TypeOf((*MockClient)(nil).GetAssetPairs), ctx)
}

// GetAssets mocks base method.
func (m *MockClient) GetAssets(ctx context.Context) (map[string]AssetInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssets", ctx)
	ret0, _ := ret[0].(map[string]AssetInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssets indicates an expected call of GetAssets.
func (mr *MockClientMockRecorder) GetAssets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssets", reflect.TypeOf((*MockClient)(nil).GetAssets), ctx)
}

// GetBalanceEx mocks base method.
func (m *MockClient) GetBalanceEx(ctx context.Context) (map[string]BalanceExEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceEx", ctx)
	ret0, _ := ret[0].(map[string]BalanceExEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceEx indicates an expected call of GetBalanceEx.
func (mr *MockClientMockRecorder) GetBalanceEx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceEx", reflect.TypeOf((*MockClient)(nil).GetBalanceEx), ctx)
}

// GetClosedOrders mocks base method.
func (m *MockClient) GetClosedOrders(ctx context.Context, params ClosedOrdersParams) (ClosedOrdersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClosedOrders", ctx, params)
	ret0, _ := ret[0].(ClosedOrdersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClosedOrders indicates an expected call of GetClosedOrders.
func (mr *MockClientMockRecorder) GetClosedOrders(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClosedOrders", reflect.TypeOf((*MockClient)(nil).GetClosedOrders), ctx, params)
}

// GetLedgers mocks base method.
func (m *MockClient) GetLedgers(ctx context.Context, params LedgersParams) (LedgersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLedgers", ctx, params)
	ret0, _ := ret[0].(LedgersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedgers indicates an expected call of GetLedgers.
func (mr *MockClientMockRecorder) GetLedgers(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedgers", reflect.TypeOf((*MockClient)(nil).GetLedgers), ctx, params)
}
