ignore:
  - "pkg/events"
  - "pkg/testserver"
  - "test"
  - "tools"
  - "openapi"
  - "local_env"
  - "internal/storage/storage_generated.go"
  - "internal/connectors/engine/engine_generated.go"
  - "internal/connectors/engine/activities/client_generated.go"
  - "internal/connectors/engine/activities/schedule_client_generated.go"
  - "internal/connectors/engine/activities/workflow_run_generated.go"
  - "internal/connectors/engine/plugins/plugin_generated.go"
  - "internal/api/backend/backend_generated.go"
