ignore:
  - "pkg/client"
  - "pkg/events"
  - "pkg/testserver"
  - "test"
  - "tools"
  - "openapi"
  - "local_env"
  - "internal/storage/storage_generated.go"
  - "internal/connectors/engine/engine_generated.go"
  - "internal/connectors/engine/activities/client_generated.go"
  - "internal/connectors/engine/activities/schedule_client_generated.go"
  - "internal/connectors/engine/activities/workflow_run_generated.go"
  - "internal/connectors/engine/plugins/plugin_generated.go"
  - "internal/connectors/plugins/public/adyen/client/client_generated.go"
  - "internal/connectors/plugins/public/atlar/client/client_generated.go"
  - "internal/connectors/plugins/public/bankingcircle/client/client_generated.go"
  - "internal/connectors/plugins/public/currencycloud/client/client_generated.go"
  - "internal/connectors/plugins/public/mangopay/client/client_generated.go"
  - "internal/connectors/plugins/public/modulr/client/client_generated.go"
  - "internal/connectors/plugins/public/moneycorp/client/client_generated.go"
  - "internal/connectors/plugins/public/stripe/client/client_generated.go"
  - "internal/connectors/plugins/public/wise/client/client_generated.go"
  - "internal/api/backend/backend_generated.go"
