# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
project_name: payments

includes:
  - from_url:
      url: https://raw.githubusercontent.com/formancehq/earthly/refs/heads/main/.goreleaser.default.yaml

builds:
  - binary: payments
    id: payments-ce
    ldflags:
      - -X github.com/formancehq/payments/cmd.BuildDate={{ .Date }}
      - -X github.com/formancehq/payments/cmd.Version=v{{ .Version }}
      - -X github.com/formancehq/payments/cmd.Commit={{ .ShortCommit }}
      - -X github.com/formancehq/payments/cmd.Edition=community
      - -extldflags "-static"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - binary: payments
    id: payments-ee
    tags:
      - ee
    ldflags:
      - -X github.com/formancehq/payments/cmd.BuildDate={{ .Date }}
      - -X github.com/formancehq/payments/cmd.Version=v{{ .Version }}
      - -X github.com/formancehq/payments/cmd.Commit={{ .ShortCommit }}
      - -X github.com/formancehq/payments/cmd.Edition=enterprise
      - -extldflags "-static"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: payments-ce
    builds:
      - payments-ce
    format: tar.gz
    name_template: "{{.ProjectName}}_{{.Os}}-{{.Arch}}"

  - id: payments-ee
    builds:
      - payments-ee
    format: tar.gz
    name_template: "{{.ProjectName}}-ee_{{.Os}}-{{.Arch}}"

release:
  prerelease: auto
  footer: |
    ## What to do next?
    - Read the [documentation](https://docs.formance.com/)
    - Join our [GitHub Discussions](https://github.com/orgs/formancehq/discussions)
