// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AccountsCursorCursor struct {
	PageSize int64     `json:"pageSize"`
	HasMore  bool      `json:"hasMore"`
	Previous *string   `json:"previous,omitempty"`
	Next     *string   `json:"next,omitempty"`
	Data     []Account `json:"data"`
}

func (o *AccountsCursorCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *AccountsCursorCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *AccountsCursorCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *AccountsCursorCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *AccountsCursorCursor) GetData() []Account {
	if o == nil {
		return []Account{}
	}
	return o.Data
}

// AccountsCursor - OK
type AccountsCursor struct {
	Cursor AccountsCursorCursor `json:"cursor"`
}

func (o *AccountsCursor) GetCursor() AccountsCursorCursor {
	if o == nil {
		return AccountsCursorCursor{}
	}
	return o.Cursor
}
