// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BalancesCursorCursor struct {
	PageSize int64            `json:"pageSize"`
	HasMore  bool             `json:"hasMore"`
	Previous *string          `json:"previous,omitempty"`
	Next     *string          `json:"next,omitempty"`
	Data     []AccountBalance `json:"data"`
}

func (o *BalancesCursorCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *BalancesCursorCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *BalancesCursorCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *BalancesCursorCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *BalancesCursorCursor) GetData() []AccountBalance {
	if o == nil {
		return []AccountBalance{}
	}
	return o.Data
}

// BalancesCursor - OK
type BalancesCursor struct {
	Cursor BalancesCursorCursor `json:"cursor"`
}

func (o *BalancesCursor) GetCursor() BalancesCursorCursor {
	if o == nil {
		return BalancesCursorCursor{}
	}
	return o.Cursor
}
