// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// BankAccountResponse - OK
type BankAccountResponse struct {
	Data BankAccount `json:"data"`
}

func (o *BankAccountResponse) GetData() BankAccount {
	if o == nil {
		return BankAccount{}
	}
	return o.Data
}
