// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BankAccountsCursorCursor struct {
	PageSize int64         `json:"pageSize"`
	HasMore  bool          `json:"hasMore"`
	Previous *string       `json:"previous,omitempty"`
	Next     *string       `json:"next,omitempty"`
	Data     []BankAccount `json:"data"`
}

func (o *BankAccountsCursorCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *BankAccountsCursorCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *BankAccountsCursorCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *BankAccountsCursorCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *BankAccountsCursorCursor) GetData() []BankAccount {
	if o == nil {
		return []BankAccount{}
	}
	return o.Data
}

// BankAccountsCursor - OK
type BankAccountsCursor struct {
	Cursor BankAccountsCursorCursor `json:"cursor"`
}

func (o *BankAccountsCursor) GetCursor() BankAccountsCursorCursor {
	if o == nil {
		return BankAccountsCursorCursor{}
	}
	return o.Cursor
}
