// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ConnectorsResponseDatum struct {
	Provider    ConnectorEnum `json:"provider"`
	Name        string        `json:"name"`
	ConnectorID string        `json:"connectorID"`
	Enabled     *bool         `json:"enabled,omitempty"`
}

func (o *ConnectorsResponseDatum) GetProvider() ConnectorEnum {
	if o == nil {
		return ConnectorEnum("")
	}
	return o.Provider
}

func (o *ConnectorsResponseDatum) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ConnectorsResponseDatum) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *ConnectorsResponseDatum) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

// ConnectorsResponse - OK
type ConnectorsResponse struct {
	Data []ConnectorsResponseDatum `json:"data"`
}

func (o *ConnectorsResponse) GetData() []ConnectorsResponseDatum {
	if o == nil {
		return []ConnectorsResponseDatum{}
	}
	return o.Data
}
