// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ConnectorsConfigsResponseKey struct {
	DataType string `json:"dataType"`
	Required bool   `json:"required"`
}

func (o *ConnectorsConfigsResponseKey) GetDataType() string {
	if o == nil {
		return ""
	}
	return o.DataType
}

func (o *ConnectorsConfigsResponseKey) GetRequired() bool {
	if o == nil {
		return false
	}
	return o.Required
}

type ConnectorsConfigsResponseConnector struct {
	Key ConnectorsConfigsResponseKey `json:"key"`
}

func (o *ConnectorsConfigsResponseConnector) GetKey() ConnectorsConfigsResponseKey {
	if o == nil {
		return ConnectorsConfigsResponseKey{}
	}
	return o.Key
}

type ConnectorsConfigsResponseData struct {
	Connector ConnectorsConfigsResponseConnector `json:"connector"`
}

func (o *ConnectorsConfigsResponseData) GetConnector() ConnectorsConfigsResponseConnector {
	if o == nil {
		return ConnectorsConfigsResponseConnector{}
	}
	return o.Connector
}

// ConnectorsConfigsResponse - OK
type ConnectorsConfigsResponse struct {
	Data ConnectorsConfigsResponseData `json:"data"`
}

func (o *ConnectorsConfigsResponse) GetData() ConnectorsConfigsResponseData {
	if o == nil {
		return ConnectorsConfigsResponseData{}
	}
	return o.Data
}
