// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
)

type CurrencyCloudConfig struct {
	Name     string  `json:"name"`
	Provider *string `default:"Currencycloud" json:"provider"`
	APIKey   string  `json:"apiKey"`
	// Username of the API Key holder
	LoginID string `json:"loginID"`
	// The frequency at which the connector will fetch transactions
	PollingPeriod *string `default:"120s" json:"pollingPeriod"`
	// The endpoint to use for the API. Defaults to https://devapi.currencycloud.com
	Endpoint *string `json:"endpoint,omitempty"`
}

func (c CurrencyCloudConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CurrencyCloudConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CurrencyCloudConfig) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CurrencyCloudConfig) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *CurrencyCloudConfig) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *CurrencyCloudConfig) GetLoginID() string {
	if o == nil {
		return ""
	}
	return o.LoginID
}

func (o *CurrencyCloudConfig) GetPollingPeriod() *string {
	if o == nil {
		return nil
	}
	return o.PollingPeriod
}

func (o *CurrencyCloudConfig) GetEndpoint() *string {
	if o == nil {
		return nil
	}
	return o.Endpoint
}
