// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
)

type DummyPayConfig struct {
	Name     string  `json:"name"`
	Provider *string `default:"Dummypay" json:"provider"`
	// The frequency at which the connector will try to fetch new payment objects from the directory
	FilePollingPeriod            *string `default:"10s" json:"filePollingPeriod"`
	Directory                    string  `json:"directory"`
	PrefixFileToIngest           *string `json:"prefixFileToIngest,omitempty"`
	NumberOfAccountsPreGenerated *int64  `json:"numberOfAccountsPreGenerated,omitempty"`
	NumberOfPaymentsPreGenerated *int64  `json:"numberOfPaymentsPreGenerated,omitempty"`
}

func (d DummyPayConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DummyPayConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *DummyPayConfig) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *DummyPayConfig) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *DummyPayConfig) GetFilePollingPeriod() *string {
	if o == nil {
		return nil
	}
	return o.FilePollingPeriod
}

func (o *DummyPayConfig) GetDirectory() string {
	if o == nil {
		return ""
	}
	return o.Directory
}

func (o *DummyPayConfig) GetPrefixFileToIngest() *string {
	if o == nil {
		return nil
	}
	return o.PrefixFileToIngest
}

func (o *DummyPayConfig) GetNumberOfAccountsPreGenerated() *int64 {
	if o == nil {
		return nil
	}
	return o.NumberOfAccountsPreGenerated
}

func (o *DummyPayConfig) GetNumberOfPaymentsPreGenerated() *int64 {
	if o == nil {
		return nil
	}
	return o.NumberOfPaymentsPreGenerated
}
