// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ForwardBankAccountRequest struct {
	// Identifier of the connector to forward the bank account to
	ConnectorID string `json:"connectorID"`
}

func (o *ForwardBankAccountRequest) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}
