// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
)

type GenericConfig struct {
	// Human-readable name identifying this connector instance
	Name string `json:"name"`
	// Identifies the payment provider this configuration targets
	Provider *string `default:"Generic" json:"provider"`
	// API key used to authenticate the connector's requests
	APIKey string `json:"apiKey"`
	// Base URL of the API the connector calls
	Endpoint string `json:"endpoint"`
	// The frequency at which the connector will try to fetch new BalanceTransaction objects from the API.
	//
	PollingPeriod *string `default:"30m" json:"pollingPeriod"`
}

func (g GenericConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GenericConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GenericConfig) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *GenericConfig) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *GenericConfig) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *GenericConfig) GetEndpoint() string {
	if o == nil {
		return ""
	}
	return o.Endpoint
}

func (o *GenericConfig) GetPollingPeriod() *string {
	if o == nil {
		return nil
	}
	return o.PollingPeriod
}
