// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
)

type MangoPayConfig struct {
	// Human-readable name identifying this connector instance
	Name string `json:"name"`
	// Identifies the payment provider this configuration targets
	Provider *string `default:"Mangopay" json:"provider"`
	// The frequency at which the connector will try to fetch new BalanceTransaction objects from MangoPay API.
	//
	PollingPeriod *string `default:"30m" json:"pollingPeriod"`
	// Client ID issued by MangoPay
	ClientID string `json:"clientID"`
	// API key issued by MangoPay, used to authenticate the connector's requests
	APIKey string `json:"apiKey"`
	// Base URL of the MangoPay API the connector calls
	Endpoint string `json:"endpoint"`
}

func (m MangoPayConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MangoPayConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *MangoPayConfig) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *MangoPayConfig) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *MangoPayConfig) GetPollingPeriod() *string {
	if o == nil {
		return nil
	}
	return o.PollingPeriod
}

func (o *MangoPayConfig) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *MangoPayConfig) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *MangoPayConfig) GetEndpoint() string {
	if o == nil {
		return ""
	}
	return o.Endpoint
}
