// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
)

type ModulrConfig struct {
	// Human-readable name identifying this connector instance
	Name string `json:"name"`
	// Identifies the payment provider this configuration targets
	Provider *string `default:"Modulr" json:"provider"`
	// API key issued by Modulr, used to authenticate the connector's requests
	APIKey string `json:"apiKey"`
	// API secret issued by Modulr, paired with the API key to sign requests
	APISecret string `json:"apiSecret"`
	// Base URL of the Modulr API the connector calls
	Endpoint *string `json:"endpoint,omitempty"`
	// The frequency at which the connector will try to fetch new BalanceTransaction objects from Modulr API.
	//
	PollingPeriod *string `default:"30m" json:"pollingPeriod"`
}

func (m ModulrConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *ModulrConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ModulrConfig) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ModulrConfig) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *ModulrConfig) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *ModulrConfig) GetAPISecret() string {
	if o == nil {
		return ""
	}
	return o.APISecret
}

func (o *ModulrConfig) GetEndpoint() *string {
	if o == nil {
		return nil
	}
	return o.Endpoint
}

func (o *ModulrConfig) GetPollingPeriod() *string {
	if o == nil {
		return nil
	}
	return o.PollingPeriod
}
