// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
)

type ModulrConfig struct {
	Name      string  `json:"name"`
	Provider  *string `default:"Modulr" json:"provider"`
	APIKey    string  `json:"apiKey"`
	APISecret string  `json:"apiSecret"`
	Endpoint  *string `json:"endpoint,omitempty"`
	// The frequency at which the connector will try to fetch new BalanceTransaction objects from Modulr API.
	//
	PollingPeriod *string `default:"120s" json:"pollingPeriod"`
}

func (m ModulrConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *ModulrConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ModulrConfig) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ModulrConfig) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *ModulrConfig) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *ModulrConfig) GetAPISecret() string {
	if o == nil {
		return ""
	}
	return o.APISecret
}

func (o *ModulrConfig) GetEndpoint() *string {
	if o == nil {
		return nil
	}
	return o.Endpoint
}

func (o *ModulrConfig) GetPollingPeriod() *string {
	if o == nil {
		return nil
	}
	return o.PollingPeriod
}
