// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// PaymentsErrorsEnum - Machine-readable error code identifying the failure
type PaymentsErrorsEnum string

const (
	PaymentsErrorsEnumInternal                        PaymentsErrorsEnum = "INTERNAL"
	PaymentsErrorsEnumValidation                      PaymentsErrorsEnum = "VALIDATION"
	PaymentsErrorsEnumInvalidID                       PaymentsErrorsEnum = "INVALID_ID"
	PaymentsErrorsEnumMissingOrInvalidBody            PaymentsErrorsEnum = "MISSING_OR_INVALID_BODY"
	PaymentsErrorsEnumConflict                        PaymentsErrorsEnum = "CONFLICT"
	PaymentsErrorsEnumConnectorCapabilityNotSupported PaymentsErrorsEnum = "CONNECTOR_CAPABILITY_NOT_SUPPORTED"
	PaymentsErrorsEnumNotFound                        PaymentsErrorsEnum = "NOT_FOUND"
)

func (e PaymentsErrorsEnum) ToPointer() *PaymentsErrorsEnum {
	return &e
}
func (e *PaymentsErrorsEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "INTERNAL":
		fallthrough
	case "VALIDATION":
		fallthrough
	case "INVALID_ID":
		fallthrough
	case "MISSING_OR_INVALID_BODY":
		fallthrough
	case "CONFLICT":
		fallthrough
	case "CONNECTOR_CAPABILITY_NOT_SUPPORTED":
		fallthrough
	case "NOT_FOUND":
		*e = PaymentsErrorsEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentsErrorsEnum: %v", v)
	}
}
