// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PaymentResponse - OK
type PaymentResponse struct {
	// A payment observed at a provider and surfaced through a connector
	Data Payment `json:"data"`
}

func (o *PaymentResponse) GetData() Payment {
	if o == nil {
		return Payment{}
	}
	return o.Data
}
