// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
	"math/big"
	"time"
)

type PaymentRequest struct {
	Reference            string        `json:"reference"`
	ConnectorID          string        `json:"connectorID"`
	CreatedAt            time.Time     `json:"createdAt"`
	Amount               *big.Int      `json:"amount"`
	Type                 PaymentType   `json:"type"`
	Status               PaymentStatus `json:"status"`
	Scheme               PaymentScheme `json:"scheme"`
	Asset                string        `json:"asset"`
	SourceAccountID      *string       `json:"sourceAccountID,omitempty"`
	DestinationAccountID *string       `json:"destinationAccountID,omitempty"`
}

func (p PaymentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaymentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *PaymentRequest) GetReference() string {
	if o == nil {
		return ""
	}
	return o.Reference
}

func (o *PaymentRequest) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *PaymentRequest) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *PaymentRequest) GetAmount() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.Amount
}

func (o *PaymentRequest) GetType() PaymentType {
	if o == nil {
		return PaymentType("")
	}
	return o.Type
}

func (o *PaymentRequest) GetStatus() PaymentStatus {
	if o == nil {
		return PaymentStatus("")
	}
	return o.Status
}

func (o *PaymentRequest) GetScheme() PaymentScheme {
	if o == nil {
		return PaymentScheme("")
	}
	return o.Scheme
}

func (o *PaymentRequest) GetAsset() string {
	if o == nil {
		return ""
	}
	return o.Asset
}

func (o *PaymentRequest) GetSourceAccountID() *string {
	if o == nil {
		return nil
	}
	return o.SourceAccountID
}

func (o *PaymentRequest) GetDestinationAccountID() *string {
	if o == nil {
		return nil
	}
	return o.DestinationAccountID
}
