// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PaymentsCursorCursor - Paginated cursor wrapping the list of payments
type PaymentsCursorCursor struct {
	// Number of items requested per page
	PageSize int64 `json:"pageSize"`
	// Whether further pages are available
	HasMore bool `json:"hasMore"`
	// Cursor for the previous page, absent on the first page
	Previous *string `json:"previous,omitempty"`
	// Cursor for the next page, absent on the last page
	Next *string   `json:"next,omitempty"`
	Data []Payment `json:"data"`
}

func (o *PaymentsCursorCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *PaymentsCursorCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *PaymentsCursorCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *PaymentsCursorCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *PaymentsCursorCursor) GetData() []Payment {
	if o == nil {
		return []Payment{}
	}
	return o.Data
}

// PaymentsCursor - OK
type PaymentsCursor struct {
	// Paginated cursor wrapping the list of payments
	Cursor PaymentsCursorCursor `json:"cursor"`
}

func (o *PaymentsCursor) GetCursor() PaymentsCursorCursor {
	if o == nil {
		return PaymentsCursorCursor{}
	}
	return o.Cursor
}
