// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
	"math/big"
	"time"
)

// Payment - A payment observed at a provider and surfaced through a connector
type Payment struct {
	// Unique identifier of the payment within Formance
	ID string `json:"id"`
	// Identifier the payment carries at the provider
	Reference string `json:"reference"`
	// Identifier of the account the funds left
	SourceAccountID string `json:"sourceAccountID"`
	// Identifier of the account the funds reached
	DestinationAccountID string `json:"destinationAccountID"`
	// Identifier of the connector the payment belongs to
	ConnectorID string `json:"connectorID"`
	// The payment provider behind a connector
	Provider *Connector `json:"provider,omitempty"`
	// Direction of a payment
	Type PaymentType `json:"type"`
	// Where a payment stands in its lifecycle
	Status PaymentStatus `json:"status"`
	// Amount the payment was created with, before any adjustment
	InitialAmount *big.Int `json:"initialAmount"`
	// Current amount of the payment after applying its adjustments
	Amount *big.Int `json:"amount"`
	// Payment scheme or rail a payment travels over
	Scheme PaymentScheme `json:"scheme"`
	// Asset the payment is denominated in
	Asset string `json:"asset"`
	// When the payment was created at the provider
	CreatedAt time.Time `json:"createdAt"`
	// The provider's original payload, passed through untouched
	Raw map[string]any `json:"raw"`
	// Successive changes to the payment's amount and status
	Adjustments []PaymentAdjustment `json:"adjustments"`
	// Arbitrary key/value pairs attached to the payment
	Metadata map[string]string `json:"metadata"`
}

func (p Payment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Payment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Payment) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Payment) GetReference() string {
	if o == nil {
		return ""
	}
	return o.Reference
}

func (o *Payment) GetSourceAccountID() string {
	if o == nil {
		return ""
	}
	return o.SourceAccountID
}

func (o *Payment) GetDestinationAccountID() string {
	if o == nil {
		return ""
	}
	return o.DestinationAccountID
}

func (o *Payment) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *Payment) GetProvider() *Connector {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *Payment) GetType() PaymentType {
	if o == nil {
		return PaymentType("")
	}
	return o.Type
}

func (o *Payment) GetStatus() PaymentStatus {
	if o == nil {
		return PaymentStatus("")
	}
	return o.Status
}

func (o *Payment) GetInitialAmount() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.InitialAmount
}

func (o *Payment) GetAmount() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.Amount
}

func (o *Payment) GetScheme() PaymentScheme {
	if o == nil {
		return PaymentScheme("")
	}
	return o.Scheme
}

func (o *Payment) GetAsset() string {
	if o == nil {
		return ""
	}
	return o.Asset
}

func (o *Payment) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *Payment) GetRaw() map[string]any {
	if o == nil {
		return nil
	}
	return o.Raw
}

func (o *Payment) GetAdjustments() []PaymentAdjustment {
	if o == nil {
		return []PaymentAdjustment{}
	}
	return o.Adjustments
}

func (o *Payment) GetMetadata() map[string]string {
	if o == nil {
		return nil
	}
	return o.Metadata
}
