// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PoolRequest struct {
	Name       string   `json:"name"`
	AccountIDs []string `json:"accountIDs"`
}

func (o *PoolRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PoolRequest) GetAccountIDs() []string {
	if o == nil {
		return []string{}
	}
	return o.AccountIDs
}
