// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PoolRequest - Query and dynamic pools are available from Connectivity v3.1
type PoolRequest struct {
	// Human-readable name for the pool
	Name string `json:"name"`
	// The same query as in ListAccount. Allowed properties are id, reference, connector_id, type, default_asset, name, psu_id, open_banking_connection_id and metadata.
	Query map[string]any `json:"query,omitempty"`
	// Accounts to place in the pool. Omit when the pool is driven by a query
	AccountIDs []string `json:"accountIDs,omitempty"`
}

func (o *PoolRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PoolRequest) GetQuery() map[string]any {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *PoolRequest) GetAccountIDs() []string {
	if o == nil {
		return nil
	}
	return o.AccountIDs
}
