// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Pool - A named group of accounts whose balances are aggregated together
type Pool struct {
	// Unique identifier of the pool
	ID string `json:"id"`
	// Human-readable name of the pool
	Name string `json:"name"`
	// Whether a pool holds a fixed account list or is driven by a query
	Type *PoolTypeEnum `json:"type,omitempty"`
	// Filter selecting the accounts a dynamic pool contains
	Query map[string]any `json:"query,omitempty"`
	// Accounts currently in the pool
	Accounts []string `json:"accounts"`
}

func (o *Pool) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Pool) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Pool) GetType() *PoolTypeEnum {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *Pool) GetQuery() map[string]any {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *Pool) GetAccounts() []string {
	if o == nil {
		return []string{}
	}
	return o.Accounts
}
