// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PoolsCursorCursor - Paginated cursor wrapping the list of pools
type PoolsCursorCursor struct {
	// Number of items requested per page
	PageSize int64 `json:"pageSize"`
	// Whether further pages are available
	HasMore bool `json:"hasMore"`
	// Cursor for the previous page, absent on the first page
	Previous *string `json:"previous,omitempty"`
	// Cursor for the next page, absent on the last page
	Next *string `json:"next,omitempty"`
	Data []Pool  `json:"data"`
}

func (o *PoolsCursorCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *PoolsCursorCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *PoolsCursorCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *PoolsCursorCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *PoolsCursorCursor) GetData() []Pool {
	if o == nil {
		return []Pool{}
	}
	return o.Data
}

// PoolsCursor - OK
type PoolsCursor struct {
	// Paginated cursor wrapping the list of pools
	Cursor PoolsCursorCursor `json:"cursor"`
}

func (o *PoolsCursor) GetCursor() PoolsCursorCursor {
	if o == nil {
		return PoolsCursorCursor{}
	}
	return o.Cursor
}
