// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
	"math/big"
)

type ReverseTransferInitiationRequest struct {
	// Caller-supplied identifier for the reversal, used to deduplicate retries
	Reference string `json:"reference"`
	// Human-readable reason for the reversal
	Description string `json:"description"`
	// Amount to reverse, in the asset's smallest unit
	Amount *big.Int `json:"amount"`
	// Asset the reversal is denominated in
	Asset string `json:"asset"`
	// Arbitrary key/value pairs to attach to the reversal
	Metadata map[string]string `json:"metadata"`
}

func (r ReverseTransferInitiationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReverseTransferInitiationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ReverseTransferInitiationRequest) GetReference() string {
	if o == nil {
		return ""
	}
	return o.Reference
}

func (o *ReverseTransferInitiationRequest) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *ReverseTransferInitiationRequest) GetAmount() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.Amount
}

func (o *ReverseTransferInitiationRequest) GetAsset() string {
	if o == nil {
		return ""
	}
	return o.Asset
}

func (o *ReverseTransferInitiationRequest) GetMetadata() map[string]string {
	if o == nil {
		return nil
	}
	return o.Metadata
}
