// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
	"time"
)

type TaskMoneycorpState struct {
}

type TaskMoneycorpDescriptor struct {
	Name      *string `json:"name,omitempty"`
	Key       *string `json:"key,omitempty"`
	AccountID *string `json:"accountID,omitempty"`
}

func (o *TaskMoneycorpDescriptor) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TaskMoneycorpDescriptor) GetKey() *string {
	if o == nil {
		return nil
	}
	return o.Key
}

func (o *TaskMoneycorpDescriptor) GetAccountID() *string {
	if o == nil {
		return nil
	}
	return o.AccountID
}

type TaskMoneycorp struct {
	ID          string                  `json:"id"`
	ConnectorID string                  `json:"connectorID"`
	CreatedAt   time.Time               `json:"createdAt"`
	UpdatedAt   time.Time               `json:"updatedAt"`
	Status      TaskStatus              `json:"status"`
	State       *TaskMoneycorpState     `json:"state,omitempty"`
	Error       *string                 `json:"error,omitempty"`
	Descriptor  TaskMoneycorpDescriptor `json:"descriptor"`
}

func (t TaskMoneycorp) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskMoneycorp) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *TaskMoneycorp) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *TaskMoneycorp) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *TaskMoneycorp) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *TaskMoneycorp) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *TaskMoneycorp) GetStatus() TaskStatus {
	if o == nil {
		return TaskStatus("")
	}
	return o.Status
}

func (o *TaskMoneycorp) GetState() *TaskMoneycorpState {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *TaskMoneycorp) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *TaskMoneycorp) GetDescriptor() TaskMoneycorpDescriptor {
	if o == nil {
		return TaskMoneycorpDescriptor{}
	}
	return o.Descriptor
}
