// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
	"time"
)

// TaskModulrState - Internal progress state the task resumes from
type TaskModulrState struct {
}

type TaskModulrDescriptor struct {
	Name      *string `json:"name,omitempty"`
	Key       *string `json:"key,omitempty"`
	AccountID *string `json:"accountID,omitempty"`
}

func (o *TaskModulrDescriptor) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TaskModulrDescriptor) GetKey() *string {
	if o == nil {
		return nil
	}
	return o.Key
}

func (o *TaskModulrDescriptor) GetAccountID() *string {
	if o == nil {
		return nil
	}
	return o.AccountID
}

type TaskModulr struct {
	// Unique identifier of the task
	ID string `json:"id"`
	// Identifier of the connector the task runs against
	ConnectorID string `json:"connectorID"`
	// When the task was created
	CreatedAt time.Time `json:"createdAt"`
	// When the task was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	// Where a task stands, from pending or active through to stopped, terminated or failed
	Status TaskStatus `json:"status"`
	// Internal progress state the task resumes from
	State *TaskModulrState `json:"state,omitempty"`
	// Why the task failed, absent when it succeeded
	Error      *string              `json:"error,omitempty"`
	Descriptor TaskModulrDescriptor `json:"descriptor"`
}

func (t TaskModulr) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskModulr) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *TaskModulr) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *TaskModulr) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *TaskModulr) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *TaskModulr) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *TaskModulr) GetStatus() TaskStatus {
	if o == nil {
		return TaskStatus("")
	}
	return o.Status
}

func (o *TaskModulr) GetState() *TaskModulrState {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *TaskModulr) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *TaskModulr) GetDescriptor() TaskModulrDescriptor {
	if o == nil {
		return TaskModulrDescriptor{}
	}
	return o.Descriptor
}
