// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
	"time"
)

// TaskWiseState - Internal progress state the task resumes from
type TaskWiseState struct {
}

type TaskWiseDescriptor struct {
	Name      *string `json:"name,omitempty"`
	Key       *string `json:"key,omitempty"`
	ProfileID *int64  `json:"profileID,omitempty"`
}

func (o *TaskWiseDescriptor) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TaskWiseDescriptor) GetKey() *string {
	if o == nil {
		return nil
	}
	return o.Key
}

func (o *TaskWiseDescriptor) GetProfileID() *int64 {
	if o == nil {
		return nil
	}
	return o.ProfileID
}

type TaskWise struct {
	// Unique identifier of the task
	ID string `json:"id"`
	// Identifier of the connector the task runs against
	ConnectorID string `json:"connectorID"`
	// When the task was created
	CreatedAt time.Time `json:"createdAt"`
	// When the task was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	// Where a task stands, from pending or active through to stopped, terminated or failed
	Status TaskStatus `json:"status"`
	// Internal progress state the task resumes from
	State *TaskWiseState `json:"state,omitempty"`
	// Why the task failed, absent when it succeeded
	Error      *string            `json:"error,omitempty"`
	Descriptor TaskWiseDescriptor `json:"descriptor"`
}

func (t TaskWise) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaskWise) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *TaskWise) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *TaskWise) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *TaskWise) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *TaskWise) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *TaskWise) GetStatus() TaskStatus {
	if o == nil {
		return TaskStatus("")
	}
	return o.Status
}

func (o *TaskWise) GetState() *TaskWiseState {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *TaskWise) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *TaskWise) GetDescriptor() TaskWiseDescriptor {
	if o == nil {
		return TaskWiseDescriptor{}
	}
	return o.Descriptor
}
