// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/formancehq/payments/pkg/client/internal/utils"
	"math/big"
	"time"
)

// TransferInitiationType - Whether the funds move between your accounts or out to a third party
type TransferInitiationType string

const (
	TransferInitiationTypeTransfer TransferInitiationType = "TRANSFER"
	TransferInitiationTypePayout   TransferInitiationType = "PAYOUT"
)

func (e TransferInitiationType) ToPointer() *TransferInitiationType {
	return &e
}
func (e *TransferInitiationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "TRANSFER":
		fallthrough
	case "PAYOUT":
		*e = TransferInitiationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TransferInitiationType: %v", v)
	}
}

// TransferInitiation - A transfer Formance asked a connector to execute
type TransferInitiation struct {
	// Unique identifier of the transfer initiation
	ID string `json:"id"`
	// Caller-supplied identifier for the initiation
	Reference string `json:"reference"`
	// When the initiation was created
	CreatedAt time.Time `json:"createdAt"`
	// When the transfer is scheduled to execute
	ScheduledAt time.Time `json:"scheduledAt"`
	// Human-readable description carried with the transfer
	Description string `json:"description"`
	// Identifier of the account the funds leave
	SourceAccountID string `json:"sourceAccountID"`
	// Identifier of the account the funds reach
	DestinationAccountID string `json:"destinationAccountID"`
	// Identifier of the connector executing the transfer
	ConnectorID string `json:"connectorID"`
	// Name of the payment provider behind the connector
	Provider *string `json:"provider"`
	// Whether the funds move between your accounts or out to a third party
	Type TransferInitiationType `json:"type"`
	// Amount to move, in the asset's smallest unit
	Amount *big.Int `json:"amount"`
	// Amount the initiation was created with, before any adjustment
	InitialAmount *big.Int `json:"initialAmount"`
	// Asset the transfer is denominated in
	Asset string `json:"asset"`
	// Where a transfer initiation stands in its lifecycle
	Status TransferInitiationStatus `json:"status"`
	// Why the initiation failed, absent when it succeeded
	Error *string `json:"error,omitempty"`
	// Arbitrary key/value pairs attached to the initiation
	Metadata map[string]string `json:"metadata,omitempty"`
	// Payments produced by this initiation
	RelatedPayments []TransferInitiationPayments `json:"relatedPayments,omitempty"`
	// Successive status changes recorded against the initiation
	RelatedAdjustments []TransferInitiationAdjustments `json:"relatedAdjustments,omitempty"`
}

func (t TransferInitiation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TransferInitiation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TransferInitiation) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *TransferInitiation) GetReference() string {
	if o == nil {
		return ""
	}
	return o.Reference
}

func (o *TransferInitiation) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *TransferInitiation) GetScheduledAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.ScheduledAt
}

func (o *TransferInitiation) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *TransferInitiation) GetSourceAccountID() string {
	if o == nil {
		return ""
	}
	return o.SourceAccountID
}

func (o *TransferInitiation) GetDestinationAccountID() string {
	if o == nil {
		return ""
	}
	return o.DestinationAccountID
}

func (o *TransferInitiation) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *TransferInitiation) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *TransferInitiation) GetType() TransferInitiationType {
	if o == nil {
		return TransferInitiationType("")
	}
	return o.Type
}

func (o *TransferInitiation) GetAmount() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.Amount
}

func (o *TransferInitiation) GetInitialAmount() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.InitialAmount
}

func (o *TransferInitiation) GetAsset() string {
	if o == nil {
		return ""
	}
	return o.Asset
}

func (o *TransferInitiation) GetStatus() TransferInitiationStatus {
	if o == nil {
		return TransferInitiationStatus("")
	}
	return o.Status
}

func (o *TransferInitiation) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *TransferInitiation) GetMetadata() map[string]string {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *TransferInitiation) GetRelatedPayments() []TransferInitiationPayments {
	if o == nil {
		return nil
	}
	return o.RelatedPayments
}

func (o *TransferInitiation) GetRelatedAdjustments() []TransferInitiationAdjustments {
	if o == nil {
		return nil
	}
	return o.RelatedAdjustments
}
