// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3AccountsCursorResponseCursor struct {
	PageSize int64       `json:"pageSize"`
	HasMore  bool        `json:"hasMore"`
	Previous *string     `json:"previous,omitempty"`
	Next     *string     `json:"next,omitempty"`
	Data     []V3Account `json:"data"`
}

func (o *V3AccountsCursorResponseCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *V3AccountsCursorResponseCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *V3AccountsCursorResponseCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *V3AccountsCursorResponseCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *V3AccountsCursorResponseCursor) GetData() []V3Account {
	if o == nil {
		return []V3Account{}
	}
	return o.Data
}

type V3AccountsCursorResponse struct {
	Cursor V3AccountsCursorResponseCursor `json:"cursor"`
}

func (o *V3AccountsCursorResponse) GetCursor() V3AccountsCursorResponseCursor {
	if o == nil {
		return V3AccountsCursorResponseCursor{}
	}
	return o.Cursor
}
