// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type V3AccountTypeEnum string

const (
	V3AccountTypeEnumUnknown  V3AccountTypeEnum = "UNKNOWN"
	V3AccountTypeEnumInternal V3AccountTypeEnum = "INTERNAL"
	V3AccountTypeEnumExternal V3AccountTypeEnum = "EXTERNAL"
)

func (e V3AccountTypeEnum) ToPointer() *V3AccountTypeEnum {
	return &e
}
func (e *V3AccountTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UNKNOWN":
		fallthrough
	case "INTERNAL":
		fallthrough
	case "EXTERNAL":
		*e = V3AccountTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V3AccountTypeEnum: %v", v)
	}
}
