// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
)

// V3AccountsQueryBuilder - Query body for /v3/accounts. Filterable keys are listed on V3AccountsFilter.
type V3AccountsQueryBuilder struct {
	// Filterable properties for /v3/accounts.
	DollarMatch          *V3AccountsFilter `json:"$match,omitempty"`
	AdditionalProperties map[string]any    `additionalProperties:"true" json:"-"`
}

func (v V3AccountsQueryBuilder) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3AccountsQueryBuilder) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3AccountsQueryBuilder) GetDollarMatch() *V3AccountsFilter {
	if o == nil {
		return nil
	}
	return o.DollarMatch
}

func (o *V3AccountsQueryBuilder) GetAdditionalProperties() map[string]any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}
