// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3ApprovePaymentInitiationResponseData - The task tracking the approval, which completes asynchronously
type V3ApprovePaymentInitiationResponseData struct {
	// Since this call is asynchronous, the response will contain the ID of the task that was created to approve the payment initiation. You can use the task API to check the status of the task and get the resulting payment ID.
	//
	TaskID string `json:"taskID"`
}

func (o *V3ApprovePaymentInitiationResponseData) GetTaskID() string {
	if o == nil {
		return ""
	}
	return o.TaskID
}

type V3ApprovePaymentInitiationResponse struct {
	// The task tracking the approval, which completes asynchronously
	Data V3ApprovePaymentInitiationResponseData `json:"data"`
}

func (o *V3ApprovePaymentInitiationResponse) GetData() V3ApprovePaymentInitiationResponseData {
	if o == nil {
		return V3ApprovePaymentInitiationResponseData{}
	}
	return o.Data
}
