// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
)

// V3BankAccountsQueryBuilder - Query body for /v3/bank-accounts. Filterable keys are listed on V3BankAccountsFilter.
type V3BankAccountsQueryBuilder struct {
	// Filterable properties for /v3/bank-accounts.
	DollarMatch          *V3BankAccountsFilter `json:"$match,omitempty"`
	AdditionalProperties map[string]any        `additionalProperties:"true" json:"-"`
}

func (v V3BankAccountsQueryBuilder) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3BankAccountsQueryBuilder) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3BankAccountsQueryBuilder) GetDollarMatch() *V3BankAccountsFilter {
	if o == nil {
		return nil
	}
	return o.DollarMatch
}

func (o *V3BankAccountsQueryBuilder) GetAdditionalProperties() map[string]any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}
