// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
	"time"
)

type V3BankAccountRelatedAccount struct {
	AccountID string    `json:"accountID"`
	CreatedAt time.Time `json:"createdAt"`
}

func (v V3BankAccountRelatedAccount) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3BankAccountRelatedAccount) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3BankAccountRelatedAccount) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

func (o *V3BankAccountRelatedAccount) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}
