// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
	"math/big"
	"time"
)

type V3Conversion struct {
	ID                   string                 `json:"id"`
	ConnectorID          string                 `json:"connectorID"`
	Provider             string                 `json:"provider"`
	Reference            string                 `json:"reference"`
	CreatedAt            time.Time              `json:"createdAt"`
	UpdatedAt            time.Time              `json:"updatedAt"`
	SourceAsset          string                 `json:"sourceAsset"`
	DestinationAsset     string                 `json:"destinationAsset"`
	SourceAmount         *big.Int               `json:"sourceAmount"`
	DestinationAmount    *big.Int               `json:"destinationAmount,omitempty"`
	Fee                  *big.Int               `json:"fee,omitempty"`
	FeeAsset             *string                `json:"feeAsset,omitempty"`
	Status               V3ConversionStatusEnum `json:"status"`
	SourceAccountID      *string                `json:"sourceAccountID,omitempty"`
	DestinationAccountID *string                `json:"destinationAccountID,omitempty"`
	Metadata             map[string]string      `json:"metadata,omitempty"`
	Error                *string                `json:"error,omitempty"`
}

func (v V3Conversion) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3Conversion) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3Conversion) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *V3Conversion) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *V3Conversion) GetProvider() string {
	if o == nil {
		return ""
	}
	return o.Provider
}

func (o *V3Conversion) GetReference() string {
	if o == nil {
		return ""
	}
	return o.Reference
}

func (o *V3Conversion) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *V3Conversion) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *V3Conversion) GetSourceAsset() string {
	if o == nil {
		return ""
	}
	return o.SourceAsset
}

func (o *V3Conversion) GetDestinationAsset() string {
	if o == nil {
		return ""
	}
	return o.DestinationAsset
}

func (o *V3Conversion) GetSourceAmount() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.SourceAmount
}

func (o *V3Conversion) GetDestinationAmount() *big.Int {
	if o == nil {
		return nil
	}
	return o.DestinationAmount
}

func (o *V3Conversion) GetFee() *big.Int {
	if o == nil {
		return nil
	}
	return o.Fee
}

func (o *V3Conversion) GetFeeAsset() *string {
	if o == nil {
		return nil
	}
	return o.FeeAsset
}

func (o *V3Conversion) GetStatus() V3ConversionStatusEnum {
	if o == nil {
		return V3ConversionStatusEnum("")
	}
	return o.Status
}

func (o *V3Conversion) GetSourceAccountID() *string {
	if o == nil {
		return nil
	}
	return o.SourceAccountID
}

func (o *V3Conversion) GetDestinationAccountID() *string {
	if o == nil {
		return nil
	}
	return o.DestinationAccountID
}

func (o *V3Conversion) GetMetadata() map[string]string {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *V3Conversion) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}
