// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ConnectorCapabilityResponse struct {
	Data []V3Capability `json:"data"`
}

func (o *V3ConnectorCapabilityResponse) GetData() []V3Capability {
	if o == nil {
		return []V3Capability{}
	}
	return o.Data
}
