// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type V3ConnectionStatusEnum string

const (
	V3ConnectionStatusEnumActive V3ConnectionStatusEnum = "ACTIVE"
	V3ConnectionStatusEnumError  V3ConnectionStatusEnum = "ERROR"
)

func (e V3ConnectionStatusEnum) ToPointer() *V3ConnectionStatusEnum {
	return &e
}
func (e *V3ConnectionStatusEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACTIVE":
		fallthrough
	case "ERROR":
		*e = V3ConnectionStatusEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V3ConnectionStatusEnum: %v", v)
	}
}
