// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ConnectorSchedulesCursorResponseCursor struct {
	PageSize int64        `json:"pageSize"`
	HasMore  bool         `json:"hasMore"`
	Previous *string      `json:"previous,omitempty"`
	Next     *string      `json:"next,omitempty"`
	Data     []V3Schedule `json:"data"`
}

func (o *V3ConnectorSchedulesCursorResponseCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *V3ConnectorSchedulesCursorResponseCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *V3ConnectorSchedulesCursorResponseCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *V3ConnectorSchedulesCursorResponseCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *V3ConnectorSchedulesCursorResponseCursor) GetData() []V3Schedule {
	if o == nil {
		return []V3Schedule{}
	}
	return o.Data
}

type V3ConnectorSchedulesCursorResponse struct {
	Cursor V3ConnectorSchedulesCursorResponseCursor `json:"cursor"`
}

func (o *V3ConnectorSchedulesCursorResponse) GetCursor() V3ConnectorSchedulesCursorResponseCursor {
	if o == nil {
		return V3ConnectorSchedulesCursorResponseCursor{}
	}
	return o.Cursor
}
