// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
)

type V3ColumnConfig struct {
	APIKey        string  `json:"apiKey"`
	Endpoint      string  `json:"endpoint"`
	Name          string  `json:"name"`
	PageSize      *int64  `default:"25" json:"pageSize"`
	PollingPeriod *string `json:"pollingPeriod,omitempty"`
	Provider      *string `default:"Column" json:"provider"`
}

func (v V3ColumnConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3ColumnConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3ColumnConfig) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *V3ColumnConfig) GetEndpoint() string {
	if o == nil {
		return ""
	}
	return o.Endpoint
}

func (o *V3ColumnConfig) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *V3ColumnConfig) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *V3ColumnConfig) GetPollingPeriod() *string {
	if o == nil {
		return nil
	}
	return o.PollingPeriod
}

func (o *V3ColumnConfig) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}
