// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ConnectorCapabilitiesResponse struct {
	// Map of provider name to the capabilities its plugin advertises.
	Data map[string][]V3Capability `json:"data"`
}

func (o *V3ConnectorCapabilitiesResponse) GetData() map[string][]V3Capability {
	if o == nil {
		return map[string][]V3Capability{}
	}
	return o.Data
}
