// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
)

type V3CoinbaseConfig struct {
	APIKey    string `json:"apiKey"`
	APISecret string `json:"apiSecret"`
	Name      string `json:"name"`
	// Deprecated: From v3.1, this parameter will be ignored.
	PageSize      *int64  `default:"25" json:"pageSize"`
	Passphrase    string  `json:"passphrase"`
	PollingPeriod *string `default:"30m" json:"pollingPeriod"`
	PortfolioID   string  `json:"portfolioId"`
	Provider      *string `default:"Coinbase" json:"provider"`
}

func (v V3CoinbaseConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3CoinbaseConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3CoinbaseConfig) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *V3CoinbaseConfig) GetAPISecret() string {
	if o == nil {
		return ""
	}
	return o.APISecret
}

func (o *V3CoinbaseConfig) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *V3CoinbaseConfig) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *V3CoinbaseConfig) GetPassphrase() string {
	if o == nil {
		return ""
	}
	return o.Passphrase
}

func (o *V3CoinbaseConfig) GetPollingPeriod() *string {
	if o == nil {
		return nil
	}
	return o.PollingPeriod
}

func (o *V3CoinbaseConfig) GetPortfolioID() string {
	if o == nil {
		return ""
	}
	return o.PortfolioID
}

func (o *V3CoinbaseConfig) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}
