// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
	"math/big"
	"time"
)

type V3CreatePaymentRequest struct {
	// Identifier the payment carries at the provider
	Reference string `json:"reference"`
	// Identifier of the connector the payment belongs to
	ConnectorID string `json:"connectorID"`
	// When the payment was created at the provider
	CreatedAt time.Time `json:"createdAt"`
	// Direction of a payment
	Type V3PaymentTypeEnum `json:"type"`
	// Amount the payment was created with, before any adjustment
	InitialAmount *big.Int `json:"initialAmount"`
	// Current amount of the payment, in the asset's smallest unit
	Amount *big.Int `json:"amount"`
	// Asset the payment is denominated in
	Asset string `json:"asset"`
	// Payment scheme or rail the payment travels over
	Scheme string `json:"scheme"`
	// Identifier of the account the funds leave
	SourceAccountID *string `json:"sourceAccountID,omitempty"`
	// Identifier of the account the funds reach
	DestinationAccountID *string `json:"destinationAccountID,omitempty"`
	// Arbitrary key/value pairs attached to the resource
	Metadata map[string]string `json:"metadata,omitempty"`
	// Status and amount changes to record alongside the payment
	Adjustments []V3CreatePaymentAdjustmentRequest `json:"adjustments,omitempty"`
}

func (v V3CreatePaymentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3CreatePaymentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3CreatePaymentRequest) GetReference() string {
	if o == nil {
		return ""
	}
	return o.Reference
}

func (o *V3CreatePaymentRequest) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *V3CreatePaymentRequest) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *V3CreatePaymentRequest) GetType() V3PaymentTypeEnum {
	if o == nil {
		return V3PaymentTypeEnum("")
	}
	return o.Type
}

func (o *V3CreatePaymentRequest) GetInitialAmount() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.InitialAmount
}

func (o *V3CreatePaymentRequest) GetAmount() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.Amount
}

func (o *V3CreatePaymentRequest) GetAsset() string {
	if o == nil {
		return ""
	}
	return o.Asset
}

func (o *V3CreatePaymentRequest) GetScheme() string {
	if o == nil {
		return ""
	}
	return o.Scheme
}

func (o *V3CreatePaymentRequest) GetSourceAccountID() *string {
	if o == nil {
		return nil
	}
	return o.SourceAccountID
}

func (o *V3CreatePaymentRequest) GetDestinationAccountID() *string {
	if o == nil {
		return nil
	}
	return o.DestinationAccountID
}

func (o *V3CreatePaymentRequest) GetMetadata() map[string]string {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *V3CreatePaymentRequest) GetAdjustments() []V3CreatePaymentAdjustmentRequest {
	if o == nil {
		return nil
	}
	return o.Adjustments
}
