// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3CreatePoolRequest struct {
	Name       string         `json:"name"`
	Query      map[string]any `json:"query,omitempty"`
	AccountIDs []string       `json:"accountIDs,omitempty"`
}

func (o *V3CreatePoolRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *V3CreatePoolRequest) GetQuery() map[string]any {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *V3CreatePoolRequest) GetAccountIDs() []string {
	if o == nil {
		return nil
	}
	return o.AccountIDs
}
