// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
)

type V3CurrencycloudConfig struct {
	APIKey   string `json:"apiKey"`
	Endpoint string `json:"endpoint"`
	LoginID  string `json:"loginID"`
	Name     string `json:"name"`
	// Deprecated: From v3.1, this parameter will be ignored.
	PageSize      *int64  `default:"25" json:"pageSize"`
	PollingPeriod *string `default:"30m" json:"pollingPeriod"`
	Provider      *string `default:"Currencycloud" json:"provider"`
}

func (v V3CurrencycloudConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3CurrencycloudConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3CurrencycloudConfig) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *V3CurrencycloudConfig) GetEndpoint() string {
	if o == nil {
		return ""
	}
	return o.Endpoint
}

func (o *V3CurrencycloudConfig) GetLoginID() string {
	if o == nil {
		return ""
	}
	return o.LoginID
}

func (o *V3CurrencycloudConfig) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *V3CurrencycloudConfig) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *V3CurrencycloudConfig) GetPollingPeriod() *string {
	if o == nil {
		return nil
	}
	return o.PollingPeriod
}

func (o *V3CurrencycloudConfig) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}
