// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ErrorResponse struct {
	ErrorCode    V3ErrorsEnum `json:"errorCode"`
	ErrorMessage string       `json:"errorMessage"`
	Details      *string      `json:"details,omitempty"`
}

func (o *V3ErrorResponse) GetErrorCode() V3ErrorsEnum {
	if o == nil {
		return V3ErrorsEnum("")
	}
	return o.ErrorCode
}

func (o *V3ErrorResponse) GetErrorMessage() string {
	if o == nil {
		return ""
	}
	return o.ErrorMessage
}

func (o *V3ErrorResponse) GetDetails() *string {
	if o == nil {
		return nil
	}
	return o.Details
}
