// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ForwardPaymentServiceUserBankAccountRequest struct {
	ConnectorID string `json:"connectorID"`
}

func (o *V3ForwardPaymentServiceUserBankAccountRequest) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}
