// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3GetPaymentInitiationResponse struct {
	Data V3PaymentInitiation `json:"data"`
}

func (o *V3GetPaymentInitiationResponse) GetData() V3PaymentInitiation {
	if o == nil {
		return V3PaymentInitiation{}
	}
	return o.Data
}
