// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3GetBankAccountResponse struct {
	// A bank account registered with Formance and forwardable to connectors
	Data V3BankAccount `json:"data"`
}

func (o *V3GetBankAccountResponse) GetData() V3BankAccount {
	if o == nil {
		return V3BankAccount{}
	}
	return o.Data
}
