// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
	"math/big"
	"time"
)

type V3InitiatePaymentRequest struct {
	Reference            string                      `json:"reference"`
	ScheduledAt          time.Time                   `json:"scheduledAt"`
	ConnectorID          string                      `json:"connectorID"`
	Description          string                      `json:"description"`
	Type                 V3PaymentInitiationTypeEnum `json:"type"`
	Amount               *big.Int                    `json:"amount"`
	Asset                string                      `json:"asset"`
	SourceAccountID      *string                     `json:"sourceAccountID,omitempty"`
	DestinationAccountID *string                     `json:"destinationAccountID,omitempty"`
	Metadata             map[string]string           `json:"metadata,omitempty"`
}

func (v V3InitiatePaymentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3InitiatePaymentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3InitiatePaymentRequest) GetReference() string {
	if o == nil {
		return ""
	}
	return o.Reference
}

func (o *V3InitiatePaymentRequest) GetScheduledAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.ScheduledAt
}

func (o *V3InitiatePaymentRequest) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *V3InitiatePaymentRequest) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *V3InitiatePaymentRequest) GetType() V3PaymentInitiationTypeEnum {
	if o == nil {
		return V3PaymentInitiationTypeEnum("")
	}
	return o.Type
}

func (o *V3InitiatePaymentRequest) GetAmount() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.Amount
}

func (o *V3InitiatePaymentRequest) GetAsset() string {
	if o == nil {
		return ""
	}
	return o.Asset
}

func (o *V3InitiatePaymentRequest) GetSourceAccountID() *string {
	if o == nil {
		return nil
	}
	return o.SourceAccountID
}

func (o *V3InitiatePaymentRequest) GetDestinationAccountID() *string {
	if o == nil {
		return nil
	}
	return o.DestinationAccountID
}

func (o *V3InitiatePaymentRequest) GetMetadata() map[string]string {
	if o == nil {
		return nil
	}
	return o.Metadata
}
