// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3InitiatePaymentResponseData struct {
	// Related payment initiation object ID created.
	//
	PaymentInitiationID *string `json:"paymentInitiationID,omitempty"`
	// Will be filled if the noValidation query parameter is set to true. Since this call is asynchronous, the response will contain the ID of the task that was created to create the payment on the PSP. You can use the task API to check the status of the task and get the resulting payment ID
	//
	TaskID *string `json:"taskID,omitempty"`
}

func (o *V3InitiatePaymentResponseData) GetPaymentInitiationID() *string {
	if o == nil {
		return nil
	}
	return o.PaymentInitiationID
}

func (o *V3InitiatePaymentResponseData) GetTaskID() *string {
	if o == nil {
		return nil
	}
	return o.TaskID
}

type V3InitiatePaymentResponse struct {
	Data V3InitiatePaymentResponseData `json:"data"`
}

func (o *V3InitiatePaymentResponse) GetData() V3InitiatePaymentResponseData {
	if o == nil {
		return V3InitiatePaymentResponseData{}
	}
	return o.Data
}
