// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
)

type V3KrakenproConfig struct {
	APIKey   string  `json:"apiKey"`
	Endpoint *string `json:"endpoint,omitempty"`
	Name     string  `json:"name"`
	// Deprecated: From v3.1, this parameter will be ignored.
	PageSize      *int64  `default:"25" json:"pageSize"`
	PollingPeriod *string `default:"30m" json:"pollingPeriod"`
	PrivateKey    string  `json:"privateKey"`
	Provider      *string `default:"Krakenpro" json:"provider"`
}

func (v V3KrakenproConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3KrakenproConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3KrakenproConfig) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *V3KrakenproConfig) GetEndpoint() *string {
	if o == nil {
		return nil
	}
	return o.Endpoint
}

func (o *V3KrakenproConfig) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *V3KrakenproConfig) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *V3KrakenproConfig) GetPollingPeriod() *string {
	if o == nil {
		return nil
	}
	return o.PollingPeriod
}

func (o *V3KrakenproConfig) GetPrivateKey() string {
	if o == nil {
		return ""
	}
	return o.PrivateKey
}

func (o *V3KrakenproConfig) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}
