// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
)

// V3OpenBankingConnectionsQueryBuilder - Query body for /v3/payment-service-users/{paymentServiceUserID}/connections. Filterable keys are listed on V3OpenBankingConnectionsFilter.
type V3OpenBankingConnectionsQueryBuilder struct {
	// Filterable properties for /v3/payment-service-users/{paymentServiceUserID}/connections.
	DollarMatch          *V3OpenBankingConnectionsFilter `json:"$match,omitempty"`
	AdditionalProperties map[string]any                  `additionalProperties:"true" json:"-"`
}

func (v V3OpenBankingConnectionsQueryBuilder) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3OpenBankingConnectionsQueryBuilder) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3OpenBankingConnectionsQueryBuilder) GetDollarMatch() *V3OpenBankingConnectionsFilter {
	if o == nil {
		return nil
	}
	return o.DollarMatch
}

func (o *V3OpenBankingConnectionsQueryBuilder) GetAdditionalProperties() map[string]any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}
