// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
)

// V3OrdersQueryBuilder - Query body for /v3/orders. Filterable keys are listed on V3OrdersFilter.
type V3OrdersQueryBuilder struct {
	// Filterable properties for /v3/orders.
	DollarMatch          *V3OrdersFilter `json:"$match,omitempty"`
	AdditionalProperties map[string]any  `additionalProperties:"true" json:"-"`
}

func (v V3OrdersQueryBuilder) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3OrdersQueryBuilder) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3OrdersQueryBuilder) GetDollarMatch() *V3OrdersFilter {
	if o == nil {
		return nil
	}
	return o.DollarMatch
}

func (o *V3OrdersQueryBuilder) GetAdditionalProperties() map[string]any {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}
