// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3OrdersCursorResponseCursor struct {
	PageSize int64     `json:"pageSize"`
	HasMore  bool      `json:"hasMore"`
	Previous *string   `json:"previous,omitempty"`
	Next     *string   `json:"next,omitempty"`
	Data     []V3Order `json:"data"`
}

func (o *V3OrdersCursorResponseCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *V3OrdersCursorResponseCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *V3OrdersCursorResponseCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *V3OrdersCursorResponseCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *V3OrdersCursorResponseCursor) GetData() []V3Order {
	if o == nil {
		return []V3Order{}
	}
	return o.Data
}

type V3OrdersCursorResponse struct {
	Cursor V3OrdersCursorResponseCursor `json:"cursor"`
}

func (o *V3OrdersCursorResponse) GetCursor() V3OrdersCursorResponseCursor {
	if o == nil {
		return V3OrdersCursorResponseCursor{}
	}
	return o.Cursor
}
