// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type V3OrderStatusEnum string

const (
	V3OrderStatusEnumUnknown         V3OrderStatusEnum = "UNKNOWN"
	V3OrderStatusEnumPending         V3OrderStatusEnum = "PENDING"
	V3OrderStatusEnumOpen            V3OrderStatusEnum = "OPEN"
	V3OrderStatusEnumPartiallyFilled V3OrderStatusEnum = "PARTIALLY_FILLED"
	V3OrderStatusEnumFilled          V3OrderStatusEnum = "FILLED"
	V3OrderStatusEnumCancelled       V3OrderStatusEnum = "CANCELLED"
	V3OrderStatusEnumFailed          V3OrderStatusEnum = "FAILED"
	V3OrderStatusEnumExpired         V3OrderStatusEnum = "EXPIRED"
)

func (e V3OrderStatusEnum) ToPointer() *V3OrderStatusEnum {
	return &e
}
func (e *V3OrderStatusEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "UNKNOWN":
		fallthrough
	case "PENDING":
		fallthrough
	case "OPEN":
		fallthrough
	case "PARTIALLY_FILLED":
		fallthrough
	case "FILLED":
		fallthrough
	case "CANCELLED":
		fallthrough
	case "FAILED":
		fallthrough
	case "EXPIRED":
		*e = V3OrderStatusEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V3OrderStatusEnum: %v", v)
	}
}
