// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
	"math/big"
	"time"
)

type V3Order struct {
	ID                  string               `json:"id"`
	ConnectorID         string               `json:"connectorID"`
	Provider            string               `json:"provider"`
	Reference           string               `json:"reference"`
	CreatedAt           time.Time            `json:"createdAt"`
	UpdatedAt           time.Time            `json:"updatedAt"`
	Direction           V3OrderDirectionEnum `json:"direction"`
	SourceAsset         string               `json:"sourceAsset"`
	TargetAsset         string               `json:"targetAsset"`
	Type                V3OrderTypeEnum      `json:"type"`
	Status              V3OrderStatusEnum    `json:"status"`
	BaseQuantityOrdered *big.Int             `json:"baseQuantityOrdered"`
	BaseQuantityFilled  *big.Int             `json:"baseQuantityFilled,omitempty"`
	LimitPrice          *big.Int             `json:"limitPrice,omitempty"`
	StopPrice           *big.Int             `json:"stopPrice,omitempty"`
	TimeInForce         V3TimeInForceEnum    `json:"timeInForce"`
	ExpiresAt           *time.Time           `json:"expiresAt,omitempty"`
	Fee                 *big.Int             `json:"fee,omitempty"`
	FeeAsset            *string              `json:"feeAsset,omitempty"`
	AverageFillPrice    *big.Int             `json:"averageFillPrice,omitempty"`
	Metadata            map[string]string    `json:"metadata,omitempty"`
	Adjustments         []V3OrderAdjustment  `json:"adjustments,omitempty"`
	Error               *string              `json:"error,omitempty"`
}

func (v V3Order) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3Order) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3Order) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *V3Order) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *V3Order) GetProvider() string {
	if o == nil {
		return ""
	}
	return o.Provider
}

func (o *V3Order) GetReference() string {
	if o == nil {
		return ""
	}
	return o.Reference
}

func (o *V3Order) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *V3Order) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *V3Order) GetDirection() V3OrderDirectionEnum {
	if o == nil {
		return V3OrderDirectionEnum("")
	}
	return o.Direction
}

func (o *V3Order) GetSourceAsset() string {
	if o == nil {
		return ""
	}
	return o.SourceAsset
}

func (o *V3Order) GetTargetAsset() string {
	if o == nil {
		return ""
	}
	return o.TargetAsset
}

func (o *V3Order) GetType() V3OrderTypeEnum {
	if o == nil {
		return V3OrderTypeEnum("")
	}
	return o.Type
}

func (o *V3Order) GetStatus() V3OrderStatusEnum {
	if o == nil {
		return V3OrderStatusEnum("")
	}
	return o.Status
}

func (o *V3Order) GetBaseQuantityOrdered() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.BaseQuantityOrdered
}

func (o *V3Order) GetBaseQuantityFilled() *big.Int {
	if o == nil {
		return nil
	}
	return o.BaseQuantityFilled
}

func (o *V3Order) GetLimitPrice() *big.Int {
	if o == nil {
		return nil
	}
	return o.LimitPrice
}

func (o *V3Order) GetStopPrice() *big.Int {
	if o == nil {
		return nil
	}
	return o.StopPrice
}

func (o *V3Order) GetTimeInForce() V3TimeInForceEnum {
	if o == nil {
		return V3TimeInForceEnum("")
	}
	return o.TimeInForce
}

func (o *V3Order) GetExpiresAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ExpiresAt
}

func (o *V3Order) GetFee() *big.Int {
	if o == nil {
		return nil
	}
	return o.Fee
}

func (o *V3Order) GetFeeAsset() *string {
	if o == nil {
		return nil
	}
	return o.FeeAsset
}

func (o *V3Order) GetAverageFillPrice() *big.Int {
	if o == nil {
		return nil
	}
	return o.AverageFillPrice
}

func (o *V3Order) GetMetadata() map[string]string {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *V3Order) GetAdjustments() []V3OrderAdjustment {
	if o == nil {
		return nil
	}
	return o.Adjustments
}

func (o *V3Order) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}
