// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
	"time"
)

type V3PaymentServiceUserLinkAttempt struct {
	ID                string                                   `json:"id"`
	PsuID             string                                   `json:"psuID"`
	ConnectorID       string                                   `json:"connectorID"`
	CreatedAt         time.Time                                `json:"createdAt"`
	Status            V3OpenBankingConnectionAttemptStatusEnum `json:"status"`
	ClientRedirectURL string                                   `json:"clientRedirectURL"`
	Error             *string                                  `json:"error,omitempty"`
}

func (v V3PaymentServiceUserLinkAttempt) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3PaymentServiceUserLinkAttempt) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3PaymentServiceUserLinkAttempt) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *V3PaymentServiceUserLinkAttempt) GetPsuID() string {
	if o == nil {
		return ""
	}
	return o.PsuID
}

func (o *V3PaymentServiceUserLinkAttempt) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *V3PaymentServiceUserLinkAttempt) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *V3PaymentServiceUserLinkAttempt) GetStatus() V3OpenBankingConnectionAttemptStatusEnum {
	if o == nil {
		return V3OpenBankingConnectionAttemptStatusEnum("")
	}
	return o.Status
}

func (o *V3PaymentServiceUserLinkAttempt) GetClientRedirectURL() string {
	if o == nil {
		return ""
	}
	return o.ClientRedirectURL
}

func (o *V3PaymentServiceUserLinkAttempt) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}
