// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3PaymentInitiationsCursorResponseCursor struct {
	PageSize int64                 `json:"pageSize"`
	HasMore  bool                  `json:"hasMore"`
	Previous *string               `json:"previous,omitempty"`
	Next     *string               `json:"next,omitempty"`
	Data     []V3PaymentInitiation `json:"data"`
}

func (o *V3PaymentInitiationsCursorResponseCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *V3PaymentInitiationsCursorResponseCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *V3PaymentInitiationsCursorResponseCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *V3PaymentInitiationsCursorResponseCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *V3PaymentInitiationsCursorResponseCursor) GetData() []V3PaymentInitiation {
	if o == nil {
		return []V3PaymentInitiation{}
	}
	return o.Data
}

type V3PaymentInitiationsCursorResponse struct {
	Cursor V3PaymentInitiationsCursorResponseCursor `json:"cursor"`
}

func (o *V3PaymentInitiationsCursorResponse) GetCursor() V3PaymentInitiationsCursorResponseCursor {
	if o == nil {
		return V3PaymentInitiationsCursorResponseCursor{}
	}
	return o.Cursor
}
