// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3PaymentInitiationAdjustmentsCursorResponseCursor - Paginated cursor wrapping the initiation's adjustments
type V3PaymentInitiationAdjustmentsCursorResponseCursor struct {
	PageSize int64                           `json:"pageSize"`
	HasMore  bool                            `json:"hasMore"`
	Previous *string                         `json:"previous,omitempty"`
	Next     *string                         `json:"next,omitempty"`
	Data     []V3PaymentInitiationAdjustment `json:"data"`
}

func (o *V3PaymentInitiationAdjustmentsCursorResponseCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *V3PaymentInitiationAdjustmentsCursorResponseCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *V3PaymentInitiationAdjustmentsCursorResponseCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *V3PaymentInitiationAdjustmentsCursorResponseCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *V3PaymentInitiationAdjustmentsCursorResponseCursor) GetData() []V3PaymentInitiationAdjustment {
	if o == nil {
		return []V3PaymentInitiationAdjustment{}
	}
	return o.Data
}

type V3PaymentInitiationAdjustmentsCursorResponse struct {
	// Paginated cursor wrapping the initiation's adjustments
	Cursor V3PaymentInitiationAdjustmentsCursorResponseCursor `json:"cursor"`
}

func (o *V3PaymentInitiationAdjustmentsCursorResponse) GetCursor() V3PaymentInitiationAdjustmentsCursorResponseCursor {
	if o == nil {
		return V3PaymentInitiationAdjustmentsCursorResponseCursor{}
	}
	return o.Cursor
}
