// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3PaymentServiceUserCreateLinkResponse struct {
	// Identifier of the link attempt this URL belongs to
	AttemptID string `json:"attemptID"`
	// URL to send the user to so they can authorise the connection
	Link string `json:"link"`
}

func (o *V3PaymentServiceUserCreateLinkResponse) GetAttemptID() string {
	if o == nil {
		return ""
	}
	return o.AttemptID
}

func (o *V3PaymentServiceUserCreateLinkResponse) GetLink() string {
	if o == nil {
		return ""
	}
	return o.Link
}
