// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
	"math/big"
	"time"
)

type V3PaymentInitiationAdjustment struct {
	ID        string                        `json:"id"`
	CreatedAt time.Time                     `json:"createdAt"`
	Status    V3PaymentInitiationStatusEnum `json:"status"`
	Amount    *big.Int                      `json:"amount,omitempty"`
	Asset     *string                       `json:"asset,omitempty"`
	Error     *string                       `json:"error,omitempty"`
	Metadata  map[string]string             `json:"metadata,omitempty"`
}

func (v V3PaymentInitiationAdjustment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3PaymentInitiationAdjustment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3PaymentInitiationAdjustment) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *V3PaymentInitiationAdjustment) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *V3PaymentInitiationAdjustment) GetStatus() V3PaymentInitiationStatusEnum {
	if o == nil {
		return V3PaymentInitiationStatusEnum("")
	}
	return o.Status
}

func (o *V3PaymentInitiationAdjustment) GetAmount() *big.Int {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *V3PaymentInitiationAdjustment) GetAsset() *string {
	if o == nil {
		return nil
	}
	return o.Asset
}

func (o *V3PaymentInitiationAdjustment) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *V3PaymentInitiationAdjustment) GetMetadata() map[string]string {
	if o == nil {
		return nil
	}
	return o.Metadata
}
