// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3PaymentInitiationRelatedPaymentsCursorResponseCursor struct {
	PageSize int64       `json:"pageSize"`
	HasMore  bool        `json:"hasMore"`
	Previous *string     `json:"previous,omitempty"`
	Next     *string     `json:"next,omitempty"`
	Data     []V3Payment `json:"data"`
}

func (o *V3PaymentInitiationRelatedPaymentsCursorResponseCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *V3PaymentInitiationRelatedPaymentsCursorResponseCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *V3PaymentInitiationRelatedPaymentsCursorResponseCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *V3PaymentInitiationRelatedPaymentsCursorResponseCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *V3PaymentInitiationRelatedPaymentsCursorResponseCursor) GetData() []V3Payment {
	if o == nil {
		return []V3Payment{}
	}
	return o.Data
}

type V3PaymentInitiationRelatedPaymentsCursorResponse struct {
	Cursor V3PaymentInitiationRelatedPaymentsCursorResponseCursor `json:"cursor"`
}

func (o *V3PaymentInitiationRelatedPaymentsCursorResponse) GetCursor() V3PaymentInitiationRelatedPaymentsCursorResponseCursor {
	if o == nil {
		return V3PaymentInitiationRelatedPaymentsCursorResponseCursor{}
	}
	return o.Cursor
}
