// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
	"math/big"
)

// V3PaymentInitiationsFilter - Filterable properties for /v3/payment-initiations.
type V3PaymentInitiationsFilter struct {
	Reference            *string                        `json:"reference,omitempty"`
	ID                   *string                        `json:"id,omitempty"`
	ConnectorID          *string                        `json:"connector_id,omitempty"`
	Type                 *V3PaymentInitiationTypeEnum   `json:"type,omitempty"`
	Asset                *string                        `json:"asset,omitempty"`
	SourceAccountID      *string                        `json:"source_account_id,omitempty"`
	DestinationAccountID *string                        `json:"destination_account_id,omitempty"`
	Status               *V3PaymentInitiationStatusEnum `json:"status,omitempty"`
	Amount               *big.Int                       `json:"amount,omitempty"`
}

func (v V3PaymentInitiationsFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3PaymentInitiationsFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3PaymentInitiationsFilter) GetReference() *string {
	if o == nil {
		return nil
	}
	return o.Reference
}

func (o *V3PaymentInitiationsFilter) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *V3PaymentInitiationsFilter) GetConnectorID() *string {
	if o == nil {
		return nil
	}
	return o.ConnectorID
}

func (o *V3PaymentInitiationsFilter) GetType() *V3PaymentInitiationTypeEnum {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *V3PaymentInitiationsFilter) GetAsset() *string {
	if o == nil {
		return nil
	}
	return o.Asset
}

func (o *V3PaymentInitiationsFilter) GetSourceAccountID() *string {
	if o == nil {
		return nil
	}
	return o.SourceAccountID
}

func (o *V3PaymentInitiationsFilter) GetDestinationAccountID() *string {
	if o == nil {
		return nil
	}
	return o.DestinationAccountID
}

func (o *V3PaymentInitiationsFilter) GetStatus() *V3PaymentInitiationStatusEnum {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *V3PaymentInitiationsFilter) GetAmount() *big.Int {
	if o == nil {
		return nil
	}
	return o.Amount
}
