// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3PaymentServiceUserConnectionsCursorResponseCursor struct {
	PageSize int64                            `json:"pageSize"`
	HasMore  bool                             `json:"hasMore"`
	Previous *string                          `json:"previous,omitempty"`
	Next     *string                          `json:"next,omitempty"`
	Data     []V3PaymentServiceUserConnection `json:"data"`
}

func (o *V3PaymentServiceUserConnectionsCursorResponseCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *V3PaymentServiceUserConnectionsCursorResponseCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *V3PaymentServiceUserConnectionsCursorResponseCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *V3PaymentServiceUserConnectionsCursorResponseCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *V3PaymentServiceUserConnectionsCursorResponseCursor) GetData() []V3PaymentServiceUserConnection {
	if o == nil {
		return []V3PaymentServiceUserConnection{}
	}
	return o.Data
}

type V3PaymentServiceUserConnectionsCursorResponse struct {
	Cursor V3PaymentServiceUserConnectionsCursorResponseCursor `json:"cursor"`
}

func (o *V3PaymentServiceUserConnectionsCursorResponse) GetCursor() V3PaymentServiceUserConnectionsCursorResponseCursor {
	if o == nil {
		return V3PaymentServiceUserConnectionsCursorResponseCursor{}
	}
	return o.Cursor
}
