// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3PaymentServiceUserUpdateLinkRequest struct {
	ApplicationName   string `json:"applicationName"`
	ClientRedirectURL string `json:"clientRedirectURL"`
}

func (o *V3PaymentServiceUserUpdateLinkRequest) GetApplicationName() string {
	if o == nil {
		return ""
	}
	return o.ApplicationName
}

func (o *V3PaymentServiceUserUpdateLinkRequest) GetClientRedirectURL() string {
	if o == nil {
		return ""
	}
	return o.ClientRedirectURL
}
