// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
)

type V3PlaidConfig struct {
	ClientID      string  `json:"clientID"`
	ClientSecret  string  `json:"clientSecret"`
	IsSandbox     *bool   `json:"isSandbox,omitempty"`
	Name          string  `json:"name"`
	PollingPeriod *string `default:"2m" json:"pollingPeriod"`
	Provider      *string `default:"Plaid" json:"provider"`
}

func (v V3PlaidConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3PlaidConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3PlaidConfig) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *V3PlaidConfig) GetClientSecret() string {
	if o == nil {
		return ""
	}
	return o.ClientSecret
}

func (o *V3PlaidConfig) GetIsSandbox() *bool {
	if o == nil {
		return nil
	}
	return o.IsSandbox
}

func (o *V3PlaidConfig) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *V3PlaidConfig) GetPollingPeriod() *string {
	if o == nil {
		return nil
	}
	return o.PollingPeriod
}

func (o *V3PlaidConfig) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}
