// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
)

type V3PowensConfig struct {
	ClientID           string  `json:"clientID"`
	ClientSecret       string  `json:"clientSecret"`
	ConfigurationToken string  `json:"configurationToken"`
	Endpoint           string  `json:"endpoint"`
	Name               string  `json:"name"`
	PageSize           *int64  `default:"25" json:"pageSize"`
	PollingPeriod      *string `default:"2m" json:"pollingPeriod"`
	Provider           *string `default:"Powens" json:"provider"`
}

func (v V3PowensConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3PowensConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3PowensConfig) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *V3PowensConfig) GetClientSecret() string {
	if o == nil {
		return ""
	}
	return o.ClientSecret
}

func (o *V3PowensConfig) GetConfigurationToken() string {
	if o == nil {
		return ""
	}
	return o.ConfigurationToken
}

func (o *V3PowensConfig) GetEndpoint() string {
	if o == nil {
		return ""
	}
	return o.Endpoint
}

func (o *V3PowensConfig) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *V3PowensConfig) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *V3PowensConfig) GetPollingPeriod() *string {
	if o == nil {
		return nil
	}
	return o.PollingPeriod
}

func (o *V3PowensConfig) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}
