// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3PoolBalancesResponse struct {
	// Aggregated balances across a pool's accounts
	Data []V3PoolBalance `json:"data"`
}

func (o *V3PoolBalancesResponse) GetData() []V3PoolBalance {
	if o == nil {
		return []V3PoolBalance{}
	}
	return o.Data
}
