// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type V3PSUOpenBankingConnectionAttemptStatusEnum string

const (
	V3PSUOpenBankingConnectionAttemptStatusEnumPending   V3PSUOpenBankingConnectionAttemptStatusEnum = "pending"
	V3PSUOpenBankingConnectionAttemptStatusEnumCompleted V3PSUOpenBankingConnectionAttemptStatusEnum = "completed"
	V3PSUOpenBankingConnectionAttemptStatusEnumExited    V3PSUOpenBankingConnectionAttemptStatusEnum = "exited"
)

func (e V3PSUOpenBankingConnectionAttemptStatusEnum) ToPointer() *V3PSUOpenBankingConnectionAttemptStatusEnum {
	return &e
}
func (e *V3PSUOpenBankingConnectionAttemptStatusEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "completed":
		fallthrough
	case "exited":
		*e = V3PSUOpenBankingConnectionAttemptStatusEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V3PSUOpenBankingConnectionAttemptStatusEnum: %v", v)
	}
}
