// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
	"math/big"
)

type V3ReversePaymentInitiationRequest struct {
	Reference   string            `json:"reference"`
	Description string            `json:"description"`
	Amount      *big.Int          `json:"amount"`
	Asset       string            `json:"asset"`
	Metadata    map[string]string `json:"metadata,omitempty"`
}

func (v V3ReversePaymentInitiationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V3ReversePaymentInitiationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V3ReversePaymentInitiationRequest) GetReference() string {
	if o == nil {
		return ""
	}
	return o.Reference
}

func (o *V3ReversePaymentInitiationRequest) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *V3ReversePaymentInitiationRequest) GetAmount() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.Amount
}

func (o *V3ReversePaymentInitiationRequest) GetAsset() string {
	if o == nil {
		return ""
	}
	return o.Asset
}

func (o *V3ReversePaymentInitiationRequest) GetMetadata() map[string]string {
	if o == nil {
		return nil
	}
	return o.Metadata
}
