// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3UninstallConnectorResponseData - The task tracking the uninstall, which completes asynchronously
type V3UninstallConnectorResponseData struct {
	// Since this call is asynchronous, the response will contain the ID of the task that was created to uninstall the connector. You can use the task API to check the status of the task and get the results.
	//
	TaskID string `json:"taskID"`
}

func (o *V3UninstallConnectorResponseData) GetTaskID() string {
	if o == nil {
		return ""
	}
	return o.TaskID
}

type V3UninstallConnectorResponse struct {
	// The task tracking the uninstall, which completes asynchronously
	Data V3UninstallConnectorResponseData `json:"data"`
}

func (o *V3UninstallConnectorResponse) GetData() V3UninstallConnectorResponseData {
	if o == nil {
		return V3UninstallConnectorResponseData{}
	}
	return o.Data
}
