// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3UpdatePaymentMetadataRequest struct {
	// Arbitrary key/value pairs attached to the resource
	Metadata map[string]string `json:"metadata"`
}

func (o *V3UpdatePaymentMetadataRequest) GetMetadata() map[string]string {
	if o == nil {
		return nil
	}
	return o.Metadata
}
