// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3UpdateBankAccountMetadataRequest struct {
	Metadata map[string]string `json:"metadata"`
}

func (o *V3UpdateBankAccountMetadataRequest) GetMetadata() map[string]string {
	if o == nil {
		return nil
	}
	return o.Metadata
}
