// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
)

type WiseConfig struct {
	Name     string  `json:"name"`
	Provider *string `default:"Wise" json:"provider"`
	APIKey   string  `json:"apiKey"`
	// The frequency at which the connector will try to fetch new BalanceTransaction objects from Wise API.
	//
	PollingPeriod *string `default:"30m" json:"pollingPeriod"`
}

func (w WiseConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WiseConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *WiseConfig) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *WiseConfig) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *WiseConfig) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *WiseConfig) GetPollingPeriod() *string {
	if o == nil {
		return nil
	}
	return o.PollingPeriod
}
