openapi: 3.0.0
info:
  title: Sample API
  version: 0.1.9
servers:
- url: /
paths:
  /organizations/{organizationId}/payments:
    get:
      operationId: listPayments
      parameters:
      - explode: false
        in: path
        name: organizationId
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - explode: true
        in: query
        name: skip
        required: false
        schema:
          type: integer
        style: form
      - explode: true
        in: query
        name: sort
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Payment'
                type: array
          description: A JSON array of payments
      summary: Returns a list of payments.
      tags:
      - payments
    put:
      operationId: savePayment
      parameters:
      - explode: false
        in: path
        name: organizationId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentData'
        required: true
      responses:
        "201":
          description: A payment object was created
        "204":
          description: A payment object was updated
      summary: Persist payment
      tags:
      - payments
components:
  schemas:
    Payment:
      allOf:
      - $ref: '#/components/schemas/PaymentData'
      - $ref: '#/components/schemas/Payment_allOf'
    PaymentData:
      example:
        reference: reference
        date: 2000-01-23T04:56:07.000+00:00
        scheme: scheme
        provider: provider
        raw: '{}'
        id: id
        value:
          amount: 0
          asset: asset
        status: status
      properties:
        provider:
          type: string
        reference:
          type: string
        scheme:
          type: string
        status:
          type: string
        id:
          type: string
        value:
          $ref: '#/components/schemas/PaymentData_value'
        date:
          format: date-time
          type: string
        raw:
          type: object
      required:
      - date
      - id
      - provider
      - status
      - value
      type: object
    Payment_allOf:
      properties:
        organizationId:
          type: string
      required:
      - organizationId
      type: object
    PaymentData_value:
      example:
        amount: 0
        asset: asset
      properties:
        amount:
          type: integer
        asset:
          type: string
      required:
      - amount
      - asset
      type: object
