// Code generated by MockGen. DO NOT EDIT.
// Source: plugin_expansion.go
//
// Generated by this command:
//
//	mockgen -source plugin_expansion.go -destination plugin_expansion_generated.go -package models
//

// Package models is a generated GoMock package.
package models

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPluginWithAccountLookup is a mock of PluginWithAccountLookup interface.
type MockPluginWithAccountLookup struct {
	ctrl     *gomock.Controller
	recorder *MockPluginWithAccountLookupMockRecorder
	isgomock struct{}
}

// MockPluginWithAccountLookupMockRecorder is the mock recorder for MockPluginWithAccountLookup.
type MockPluginWithAccountLookupMockRecorder struct {
	mock *MockPluginWithAccountLookup
}

// NewMockPluginWithAccountLookup creates a new mock instance.
func NewMockPluginWithAccountLookup(ctrl *gomock.Controller) *MockPluginWithAccountLookup {
	mock := &MockPluginWithAccountLookup{ctrl: ctrl}
	mock.recorder = &MockPluginWithAccountLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPluginWithAccountLookup) EXPECT() *MockPluginWithAccountLookupMockRecorder {
	return m.recorder
}

// UseAccountLookup mocks base method.
func (m *MockPluginWithAccountLookup) UseAccountLookup(arg0 AccountLookup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UseAccountLookup", arg0)
}

// UseAccountLookup indicates an expected call of UseAccountLookup.
func (mr *MockPluginWithAccountLookupMockRecorder) UseAccountLookup(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseAccountLookup", reflect.TypeOf((*MockPluginWithAccountLookup)(nil).UseAccountLookup), arg0)
}

// MockPluginWithBootstrapOnInstall is a mock of PluginWithBootstrapOnInstall interface.
type MockPluginWithBootstrapOnInstall struct {
	ctrl     *gomock.Controller
	recorder *MockPluginWithBootstrapOnInstallMockRecorder
	isgomock struct{}
}

// MockPluginWithBootstrapOnInstallMockRecorder is the mock recorder for MockPluginWithBootstrapOnInstall.
type MockPluginWithBootstrapOnInstallMockRecorder struct {
	mock *MockPluginWithBootstrapOnInstall
}

// NewMockPluginWithBootstrapOnInstall creates a new mock instance.
func NewMockPluginWithBootstrapOnInstall(ctrl *gomock.Controller) *MockPluginWithBootstrapOnInstall {
	mock := &MockPluginWithBootstrapOnInstall{ctrl: ctrl}
	mock.recorder = &MockPluginWithBootstrapOnInstallMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPluginWithBootstrapOnInstall) EXPECT() *MockPluginWithBootstrapOnInstallMockRecorder {
	return m.recorder
}

// BootstrapOnInstall mocks base method.
func (m *MockPluginWithBootstrapOnInstall) BootstrapOnInstall() []TaskType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BootstrapOnInstall")
	ret0, _ := ret[0].([]TaskType)
	return ret0
}

// BootstrapOnInstall indicates an expected call of BootstrapOnInstall.
func (mr *MockPluginWithBootstrapOnInstallMockRecorder) BootstrapOnInstall() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BootstrapOnInstall", reflect.TypeOf((*MockPluginWithBootstrapOnInstall)(nil).BootstrapOnInstall))
}

// MockPluginWithPayoutThrottle is a mock of PluginWithPayoutThrottle interface.
type MockPluginWithPayoutThrottle struct {
	ctrl     *gomock.Controller
	recorder *MockPluginWithPayoutThrottleMockRecorder
	isgomock struct{}
}

// MockPluginWithPayoutThrottleMockRecorder is the mock recorder for MockPluginWithPayoutThrottle.
type MockPluginWithPayoutThrottleMockRecorder struct {
	mock *MockPluginWithPayoutThrottle
}

// NewMockPluginWithPayoutThrottle creates a new mock instance.
func NewMockPluginWithPayoutThrottle(ctrl *gomock.Controller) *MockPluginWithPayoutThrottle {
	mock := &MockPluginWithPayoutThrottle{ctrl: ctrl}
	mock.recorder = &MockPluginWithPayoutThrottleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPluginWithPayoutThrottle) EXPECT() *MockPluginWithPayoutThrottleMockRecorder {
	return m.recorder
}

// PayoutsPerSecond mocks base method.
func (m *MockPluginWithPayoutThrottle) PayoutsPerSecond() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PayoutsPerSecond")
	ret0, _ := ret[0].(float64)
	return ret0
}

// PayoutsPerSecond indicates an expected call of PayoutsPerSecond.
func (mr *MockPluginWithPayoutThrottleMockRecorder) PayoutsPerSecond() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PayoutsPerSecond", reflect.TypeOf((*MockPluginWithPayoutThrottle)(nil).PayoutsPerSecond))
}
