package models

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const DefaultConnectorClientTimeout = 10 * time.Second

type PluginType int

const (
	PluginTypePSP PluginType = iota
	PluginTypeOpenBanking
	PluginTypeBoth
)

//go:generate mockgen -source plugin.go -destination plugin_generated.go -package models . Plugin
type Plugin interface {
	PSPPlugin
	OpenBankingPlugin

	// Common methods
	Name() string
	Install(context.Context, InstallRequest) (InstallResponse, error)
	Uninstall(context.Context, UninstallRequest) (UninstallResponse, error)

	CreateWebhooks(context.Context, CreateWebhooksRequest) (CreateWebhooksResponse, error)
	TrimWebhook(context.Context, TrimWebhookRequest) (TrimWebhookResponse, error)
	VerifyWebhook(context.Context, VerifyWebhookRequest) (VerifyWebhookResponse, error)
	TranslateWebhook(context.Context, TranslateWebhookRequest) (TranslateWebhookResponse, error)
}

type InstallRequest struct {
	ConnectorID string
}

type InstallResponse struct {
	Workflow ConnectorTasksTree
}

type UninstallRequest struct {
	ConnectorID    string
	WebhookConfigs []PSPWebhookConfig
}

type UninstallResponse struct{}

type CreateWebhooksRequest struct {
	FromPayload    json.RawMessage
	ConnectorID    string
	WebhookBaseUrl string
}

type CreateWebhooksResponse struct {
	Configs []PSPWebhookConfig
	Others  []PSPOther // used by plugin workflow
}

type TrimWebhookRequest struct {
	Webhook PSPWebhook
	Config  *WebhookConfig
}

type TrimWebhookResponse struct {
	Webhooks []PSPWebhook
}

type VerifyWebhookRequest struct {
	Webhook PSPWebhook
	Config  *WebhookConfig
}

type VerifyWebhookResponse struct {
	WebhookIdempotencyKey *string
}

type TranslateWebhookRequest struct {
	Name    string
	Webhook PSPWebhook
	Config  *WebhookConfig
}

type TranslateWebhookResponse struct {
	Responses []WebhookResponse
}

type WebhookResponse struct {
	Account         *PSPAccount
	ExternalAccount *PSPAccount
	Payment         *PSPPayment
	PaymentToDelete *PSPPaymentsToDelete
	PaymentToCancel *PSPPaymentsToCancel

	OpenBankingAccount *PSPOpenBankingAccount
	OpenBankingPayment *PSPOpenBankingPayment

	// Webhooks related to open banking
	UserLinkSessionFinished         *PSPUserLinkSessionFinished
	DataReadyToFetch                *PSPDataReadyToFetch
	UserDisconnected                *PSPUserDisconnected
	UserConnectionPendingDisconnect *PSPUserConnectionPendingDisconnect
	UserConnectionDisconnected      *PSPUserConnectionDisconnected
	UserConnectionReconnected       *PSPUserConnectionReconnected
}

type PSPDataReadyToFetch struct {
	PSUID        *uuid.UUID
	ConnectionID *string
	FromPayload  json.RawMessage
}

type PSPDataToDelete struct {
	ConnectionID string

	// If filled, the account and all its data will be deleted. The connection
	// ID will still be available in the database.
	// If not filled, all data associated with the connection will be deleted.
	AccountID *string

	FromPayload json.RawMessage
}

type PSPUserDisconnected struct {
	// The user ID is the ID of the user that was disconnected. It should
	// correspond to the ID putting in the metadata of the aggregator, since
	// it's something generated by the PSP.
	UserID string
}

type PSPUserConnectionPendingDisconnect struct {
	ConnectionID string
	At           time.Time
	Reason       *string
}

type UserConnectionPendingDisconnect struct {
	PsuID        uuid.UUID
	ConnectorID  ConnectorID
	ConnectionID string
	At           time.Time
	Reason       *string
}

func (u UserConnectionPendingDisconnect) IdempotencyKey() string {
	return IdempotencyKey(u)
}

type PSPUserConnectionDisconnected struct {
	ConnectionID string
	At           time.Time
	Reason       *string
}

type PSPUserConnectionReconnected struct {
	ConnectionID string
	At           time.Time
}

type UserDisconnected struct {
	PsuID       uuid.UUID
	ConnectorID ConnectorID
	At          time.Time
	Reason      *string
}

func (u UserDisconnected) IdempotencyKey() string {
	return IdempotencyKey(u)
}

type UserConnectionDisconnected struct {
	PsuID        uuid.UUID
	ConnectorID  ConnectorID
	ConnectionID string
	At           time.Time
	Reason       *string
}

func (u UserConnectionDisconnected) IdempotencyKey() string {
	return IdempotencyKey(u)
}

type UserConnectionReconnected struct {
	PsuID        uuid.UUID
	ConnectorID  ConnectorID
	ConnectionID string
	At           time.Time
}

func (u UserConnectionReconnected) IdempotencyKey() string {
	return IdempotencyKey(u)
}

type PSPUserLinkSessionFinished struct {
	AttemptID uuid.UUID
	Status    PSUOpenBankingConnectionAttemptStatus
	Error     *string
}

type UserLinkSessionFinished struct {
	PsuID       uuid.UUID
	ConnectorID ConnectorID
	AttemptID   uuid.UUID
	Status      PSUOpenBankingConnectionAttemptStatus
	Error       *string
}

func (u UserLinkSessionFinished) IdempotencyKey() string {
	return IdempotencyKey(u)
}

type UserConnectionDataSynced struct {
	PsuID        uuid.UUID
	ConnectorID  ConnectorID
	ConnectionID string
	At           time.Time
}

func (u UserConnectionDataSynced) IdempotencyKey() string {
	return IdempotencyKey(u)
}

type OpenBankingProviderPSUFromPayload struct {
	OpenBankingProviderPSU   *OpenBankingProviderPSU
	PSUOpenBankingConnection *PSUOpenBankingConnection
	FromPayload              json.RawMessage
}
