package models

import (
	"time"

	"github.com/google/uuid"
)

const (
	NoRedirectQueryParamID = "noRedirect"
)

type PSUBankBridgeConnectionAttemptStatus string

const (
	PSUBankBridgeConnectionAttemptStatusPending   PSUBankBridgeConnectionAttemptStatus = "pending"
	PSUBankBridgeConnectionAttemptStatusCompleted PSUBankBridgeConnectionAttemptStatus = "completed"
	PSUBankBridgeConnectionAttemptStatusFailed    PSUBankBridgeConnectionAttemptStatus = "failed"
)

// When a user tries to connect to a banking bridge, we will create an attempt
// in order to save some crucial information.
type PSUBankBridgeConnectionAttempt struct {
	// ID of the attempt
	ID uuid.UUID `json:"id"`
	// ID of the psu
	PsuID uuid.UUID `json:"psuID"`
	// Related connector ID
	ConnectorID ConnectorID `json:"connectorID"`
	// Creation date of the attempt
	CreatedAt time.Time `json:"createdAt"`
	// Status of the attempt
	Status PSUBankBridgeConnectionAttemptStatus `json:"status"`
	// State given to the url in order to be able to verify that the callback
	// is valid.
	State CallbackState `json:"state"`
	// Client redirect URL, given by the user
	ClientRedirectURL *string `json:"clientRedirectURL"`

	// Optional
	// Temporary token generated by the banking bridge in order to create an
	// url.
	TemporaryToken *Token `json:"temporaryToken"`
	// Error message in case of failure
	Error *string `json:"error"`
}

// Represents all connections of a psu for a given banking bridge (connector).
type PSUBankBridge struct {
	// ID of the connector
	ConnectorID ConnectorID `json:"connectorID"`

	// Optional
	// AccessToken is optional for some banking bridges, like Powens, where we
	// have a notion of connection, but we only have one token for all of them.
	AccessToken *Token `json:"authToken"`
	// per banking bridge additional information
	Metadata map[string]string `json:"metadata"`

	// List of connections for the same banking bridge (for example if the user
	// connects to multiple banks)
	Connections []*PSUBankBridgeConnection `json:"connections"`
}

type PSUBankBridgeConnection struct {
	// ID of the connection, given by the banking bridge
	ConnectionID string `json:"connectionID"`
	// Creation date of the connection
	CreatedAt time.Time `json:"createdAt"`

	// Optional
	// AccessToken is optional for some banking bridges, like Powens, where we
	// have a notion of connection, but we only have one token for all of them.
	AccessToken *Token `json:"accessToken"`
	// Additional information about the connection depending on the connector
	Metadata map[string]string `json:"metadata"`
}
