// Code generated by MockGen. DO NOT EDIT.
// Source: account_lookup.go
//
// Generated by this command:
//
//	mockgen -source account_lookup.go -destination account_lookup_generated.go -package models . AccountLookup
//

// Package models is a generated GoMock package.
package models

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAccountLookup is a mock of AccountLookup interface.
type MockAccountLookup struct {
	ctrl     *gomock.Controller
	recorder *MockAccountLookupMockRecorder
	isgomock struct{}
}

// MockAccountLookupMockRecorder is the mock recorder for MockAccountLookup.
type MockAccountLookupMockRecorder struct {
	mock *MockAccountLookup
}

// NewMockAccountLookup creates a new mock instance.
func NewMockAccountLookup(ctrl *gomock.Controller) *MockAccountLookup {
	mock := &MockAccountLookup{ctrl: ctrl}
	mock.recorder = &MockAccountLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountLookup) EXPECT() *MockAccountLookupMockRecorder {
	return m.recorder
}

// ListAccountsByConnector mocks base method.
func (m *MockAccountLookup) ListAccountsByConnector(ctx context.Context) ([]PSPAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountsByConnector", ctx)
	ret0, _ := ret[0].([]PSPAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccountsByConnector indicates an expected call of ListAccountsByConnector.
func (mr *MockAccountLookupMockRecorder) ListAccountsByConnector(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountsByConnector", reflect.TypeOf((*MockAccountLookup)(nil).ListAccountsByConnector), ctx)
}
