// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/payments/pkg/client/models/components"
)

type ConnectorsTransferRequest struct {
	// The name of the connector.
	Connector       components.ConnectorEnum   `pathParam:"style=simple,explode=false,name=connector"`
	TransferRequest components.TransferRequest `request:"mediaType=application/json"`
}

func (o *ConnectorsTransferRequest) GetConnector() components.ConnectorEnum {
	if o == nil {
		return components.ConnectorEnum("")
	}
	return o.Connector
}

func (o *ConnectorsTransferRequest) GetTransferRequest() components.TransferRequest {
	if o == nil {
		return components.TransferRequest{}
	}
	return o.TransferRequest
}

type ConnectorsTransferResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	TransferResponse *components.TransferResponse
	// Error
	PaymentsErrorResponse *components.PaymentsErrorResponse
}

func (o *ConnectorsTransferResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ConnectorsTransferResponse) GetTransferResponse() *components.TransferResponse {
	if o == nil {
		return nil
	}
	return o.TransferResponse
}

func (o *ConnectorsTransferResponse) GetPaymentsErrorResponse() *components.PaymentsErrorResponse {
	if o == nil {
		return nil
	}
	return o.PaymentsErrorResponse
}
