// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/payments/pkg/client/models/components"
)

type InstallConnectorRequest struct {
	// The name of the connector.
	Connector       components.Connector       `pathParam:"style=simple,explode=false,name=connector"`
	ConnectorConfig components.ConnectorConfig `request:"mediaType=application/json"`
}

func (o *InstallConnectorRequest) GetConnector() components.Connector {
	if o == nil {
		return components.Connector("")
	}
	return o.Connector
}

func (o *InstallConnectorRequest) GetConnectorConfig() components.ConnectorConfig {
	if o == nil {
		return components.ConnectorConfig{}
	}
	return o.ConnectorConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigStripe() *components.StripeConfig {
	return o.GetConnectorConfig().StripeConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigDummypay() *components.DummyPayConfig {
	return o.GetConnectorConfig().DummyPayConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigWise() *components.WiseConfig {
	return o.GetConnectorConfig().WiseConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigModulr() *components.ModulrConfig {
	return o.GetConnectorConfig().ModulrConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigCurrencycloud() *components.CurrencyCloudConfig {
	return o.GetConnectorConfig().CurrencyCloudConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigBankingcircle() *components.BankingCircleConfig {
	return o.GetConnectorConfig().BankingCircleConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigMangopay() *components.MangoPayConfig {
	return o.GetConnectorConfig().MangoPayConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigMoneycorp() *components.MoneycorpConfig {
	return o.GetConnectorConfig().MoneycorpConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigAtlar() *components.AtlarConfig {
	return o.GetConnectorConfig().AtlarConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigAdyen() *components.AdyenConfig {
	return o.GetConnectorConfig().AdyenConfig
}

func (o *InstallConnectorRequest) GetConnectorConfigGeneric() *components.GenericConfig {
	return o.GetConnectorConfig().GenericConfig
}

type InstallConnectorResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ConnectorResponse *components.ConnectorResponse
	// Error
	PaymentsErrorResponse *components.PaymentsErrorResponse
}

func (o *InstallConnectorResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *InstallConnectorResponse) GetConnectorResponse() *components.ConnectorResponse {
	if o == nil {
		return nil
	}
	return o.ConnectorResponse
}

func (o *InstallConnectorResponse) GetPaymentsErrorResponse() *components.PaymentsErrorResponse {
	if o == nil {
		return nil
	}
	return o.PaymentsErrorResponse
}
