// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/payments/pkg/client/internal/utils"
	"github.com/formancehq/payments/pkg/client/models/components"
)

type ListConnectorTasksRequest struct {
	// The name of the connector.
	Connector components.ConnectorEnum `pathParam:"style=simple,explode=false,name=connector"`
	// The maximum number of results to return per page.
	//
	PageSize *int64 `default:"15" queryParam:"style=form,explode=true,name=pageSize"`
	// Parameter used in pagination requests. Maximum page size is set to 15.
	// Set to the value of next for the next page of results.
	// Set to the value of previous for the previous page of results.
	// No other parameters can be set when this parameter is set.
	//
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (l ListConnectorTasksRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListConnectorTasksRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListConnectorTasksRequest) GetConnector() components.ConnectorEnum {
	if o == nil {
		return components.ConnectorEnum("")
	}
	return o.Connector
}

func (o *ListConnectorTasksRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *ListConnectorTasksRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type ListConnectorTasksResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	TasksCursor *components.TasksCursor
	// Error
	PaymentsErrorResponse *components.PaymentsErrorResponse
}

func (o *ListConnectorTasksResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListConnectorTasksResponse) GetTasksCursor() *components.TasksCursor {
	if o == nil {
		return nil
	}
	return o.TasksCursor
}

func (o *ListConnectorTasksResponse) GetPaymentsErrorResponse() *components.PaymentsErrorResponse {
	if o == nil {
		return nil
	}
	return o.PaymentsErrorResponse
}
