// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/payments/pkg/client/models/components"
)

type UdpateTransferInitiationStatusRequest struct {
	// The transfer ID.
	TransferID                            string                                           `pathParam:"style=simple,explode=false,name=transferId"`
	UpdateTransferInitiationStatusRequest components.UpdateTransferInitiationStatusRequest `request:"mediaType=application/json"`
}

func (o *UdpateTransferInitiationStatusRequest) GetTransferID() string {
	if o == nil {
		return ""
	}
	return o.TransferID
}

func (o *UdpateTransferInitiationStatusRequest) GetUpdateTransferInitiationStatusRequest() components.UpdateTransferInitiationStatusRequest {
	if o == nil {
		return components.UpdateTransferInitiationStatusRequest{}
	}
	return o.UpdateTransferInitiationStatusRequest
}

type UdpateTransferInitiationStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	PaymentsErrorResponse *components.PaymentsErrorResponse
}

func (o *UdpateTransferInitiationStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UdpateTransferInitiationStatusResponse) GetPaymentsErrorResponse() *components.PaymentsErrorResponse {
	if o == nil {
		return nil
	}
	return o.PaymentsErrorResponse
}
