// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/payments/pkg/client/models/components"
)

type UpdateBankAccountMetadataRequest struct {
	// The bank account ID.
	BankAccountID                    string                                      `pathParam:"style=simple,explode=false,name=bankAccountId"`
	UpdateBankAccountMetadataRequest components.UpdateBankAccountMetadataRequest `request:"mediaType=application/json"`
}

func (o *UpdateBankAccountMetadataRequest) GetBankAccountID() string {
	if o == nil {
		return ""
	}
	return o.BankAccountID
}

func (o *UpdateBankAccountMetadataRequest) GetUpdateBankAccountMetadataRequest() components.UpdateBankAccountMetadataRequest {
	if o == nil {
		return components.UpdateBankAccountMetadataRequest{}
	}
	return o.UpdateBankAccountMetadataRequest
}

type UpdateBankAccountMetadataResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	PaymentsErrorResponse *components.PaymentsErrorResponse
}

func (o *UpdateBankAccountMetadataResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateBankAccountMetadataResponse) GetPaymentsErrorResponse() *components.PaymentsErrorResponse {
	if o == nil {
		return nil
	}
	return o.PaymentsErrorResponse
}
