// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/payments/pkg/client/models/components"
)

type V3AddBankAccountToPaymentServiceUserRequest struct {
	// The payment service user ID
	PaymentServiceUserID string `pathParam:"style=simple,explode=false,name=paymentServiceUserID"`
	// The bank account ID
	BankAccountID string `pathParam:"style=simple,explode=false,name=bankAccountID"`
}

func (o *V3AddBankAccountToPaymentServiceUserRequest) GetPaymentServiceUserID() string {
	if o == nil {
		return ""
	}
	return o.PaymentServiceUserID
}

func (o *V3AddBankAccountToPaymentServiceUserRequest) GetBankAccountID() string {
	if o == nil {
		return ""
	}
	return o.BankAccountID
}

type V3AddBankAccountToPaymentServiceUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Error
	V3ErrorResponse *components.V3ErrorResponse
}

func (o *V3AddBankAccountToPaymentServiceUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3AddBankAccountToPaymentServiceUserResponse) GetV3ErrorResponse() *components.V3ErrorResponse {
	if o == nil {
		return nil
	}
	return o.V3ErrorResponse
}
