// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/payments/pkg/client/models/components"
)

type V3CreatePaymentServiceUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	V3CreatePaymentServiceUserResponse *components.V3CreatePaymentServiceUserResponse
	// Error
	V3ErrorResponse *components.V3ErrorResponse
}

func (o *V3CreatePaymentServiceUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3CreatePaymentServiceUserResponse) GetV3CreatePaymentServiceUserResponse() *components.V3CreatePaymentServiceUserResponse {
	if o == nil {
		return nil
	}
	return o.V3CreatePaymentServiceUserResponse
}

func (o *V3CreatePaymentServiceUserResponse) GetV3ErrorResponse() *components.V3ErrorResponse {
	if o == nil {
		return nil
	}
	return o.V3ErrorResponse
}
