// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/payments/pkg/client/models/components"
)

type V3DeletePaymentServiceUserRequest struct {
	// The payment service user ID
	PaymentServiceUserID string `pathParam:"style=simple,explode=false,name=paymentServiceUserID"`
}

func (o *V3DeletePaymentServiceUserRequest) GetPaymentServiceUserID() string {
	if o == nil {
		return ""
	}
	return o.PaymentServiceUserID
}

type V3DeletePaymentServiceUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Accepted
	V3PaymentServiceUserDeleteResponse *components.V3PaymentServiceUserDeleteResponse
	// Error
	V3ErrorResponse *components.V3ErrorResponse
}

func (o *V3DeletePaymentServiceUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3DeletePaymentServiceUserResponse) GetV3PaymentServiceUserDeleteResponse() *components.V3PaymentServiceUserDeleteResponse {
	if o == nil {
		return nil
	}
	return o.V3PaymentServiceUserDeleteResponse
}

func (o *V3DeletePaymentServiceUserResponse) GetV3ErrorResponse() *components.V3ErrorResponse {
	if o == nil {
		return nil
	}
	return o.V3ErrorResponse
}
