// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/payments/pkg/client/models/components"
)

type V3GetOrderRequest struct {
	// The order ID
	OrderID string `pathParam:"style=simple,explode=false,name=orderID"`
}

func (o *V3GetOrderRequest) GetOrderID() string {
	if o == nil {
		return ""
	}
	return o.OrderID
}

type V3GetOrderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	V3GetOrderResponse *components.V3GetOrderResponse
	// Error
	V3ErrorResponse *components.V3ErrorResponse
}

func (o *V3GetOrderResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3GetOrderResponse) GetV3GetOrderResponse() *components.V3GetOrderResponse {
	if o == nil {
		return nil
	}
	return o.V3GetOrderResponse
}

func (o *V3GetOrderResponse) GetV3ErrorResponse() *components.V3ErrorResponse {
	if o == nil {
		return nil
	}
	return o.V3ErrorResponse
}
