// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/payments/pkg/client/models/components"
)

type V3ListPaymentServiceUserConnectionsFromConnectorIDRequest struct {
	// The payment service user ID
	PaymentServiceUserID string `pathParam:"style=simple,explode=false,name=paymentServiceUserID"`
	// The connector ID
	ConnectorID string `pathParam:"style=simple,explode=false,name=connectorID"`
	// The number of items to return
	PageSize *int64 `queryParam:"style=form,explode=true,name=pageSize"`
	// Parameter used in pagination requests. Set to the value of next for the next page of results. Set to the value of previous for the previous page of results. No other parameters can be set when this parameter is set.
	//
	Cursor      *string        `queryParam:"style=form,explode=true,name=cursor"`
	RequestBody map[string]any `request:"mediaType=application/json"`
}

func (o *V3ListPaymentServiceUserConnectionsFromConnectorIDRequest) GetPaymentServiceUserID() string {
	if o == nil {
		return ""
	}
	return o.PaymentServiceUserID
}

func (o *V3ListPaymentServiceUserConnectionsFromConnectorIDRequest) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *V3ListPaymentServiceUserConnectionsFromConnectorIDRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *V3ListPaymentServiceUserConnectionsFromConnectorIDRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *V3ListPaymentServiceUserConnectionsFromConnectorIDRequest) GetRequestBody() map[string]any {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type V3ListPaymentServiceUserConnectionsFromConnectorIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	V3PaymentServiceUserConnectionsCursorResponse *components.V3PaymentServiceUserConnectionsCursorResponse
	// Error
	V3ErrorResponse *components.V3ErrorResponse
}

func (o *V3ListPaymentServiceUserConnectionsFromConnectorIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3ListPaymentServiceUserConnectionsFromConnectorIDResponse) GetV3PaymentServiceUserConnectionsCursorResponse() *components.V3PaymentServiceUserConnectionsCursorResponse {
	if o == nil {
		return nil
	}
	return o.V3PaymentServiceUserConnectionsCursorResponse
}

func (o *V3ListPaymentServiceUserConnectionsFromConnectorIDResponse) GetV3ErrorResponse() *components.V3ErrorResponse {
	if o == nil {
		return nil
	}
	return o.V3ErrorResponse
}
