package client

const (
	columnMetadataSpecNamespace = "com.column.spec/"

	ColumnSenderAccountNumberIdMetadataKey = columnMetadataSpecNamespace + "sender_account_number_id"

	ColumnReceiverAccountNumberIdMetadataKey = columnMetadataSpecNamespace + "receiver_account_number_id"

	ColumnMerchantNameMetadataKey         = columnMetadataSpecNamespace + "merchant_name"
	ColumnMerchantCategoryCodeMetadataKey = columnMetadataSpecNamespace + "merchant_category_code"
	ColumnAuthorizationMethodMetadataKey  = columnMetadataSpecNamespace + "authorization_method"
	ColumnInternalTransferTypeMetadataKey = columnMetadataSpecNamespace + "internal_transfer_type"
	ColumnWebsiteMetadataKey              = columnMetadataSpecNamespace + "website"

	ColumnAllowOverdraftMetadataKey = columnMetadataSpecNamespace + "allow_overdraft"
	ColumnHoldMetadataKey           = columnMetadataSpecNamespace + "hold"

	ColumnAmountConditionMetadataKey = columnMetadataSpecNamespace + "amount_condition"

	ColumnUltimateOriginatorCounterpartyIdMetadataKey = columnMetadataSpecNamespace + "ultimate_originator_counterparty_id"
	ColumnUltimateOriginatorAccountNumberMetadataKey  = columnMetadataSpecNamespace + "ultimate_originator_account_number"
	ColumnChargeBearerMetadataKey                     = columnMetadataSpecNamespace + "charge_bearer"
	ColumnFxQuoteIdMetadataKey                        = columnMetadataSpecNamespace + "fx_quote_id"
	ColumnIntermediaryBankMetadataKey                 = columnMetadataSpecNamespace + "intermediary_bank"
	ColumnMessageToBeneficiaryBankMetadataKey         = columnMetadataSpecNamespace + "message_to_beneficiary_bank"
	ColumnGeneralInfoMetadataKey                      = columnMetadataSpecNamespace + "general_info"
	ColumnBeneficiaryReferenceMetadataKey             = columnMetadataSpecNamespace + "beneficiary_reference"
	ColumnPurposeCodeMetadataKey                      = columnMetadataSpecNamespace + "purpose_code"

	ColumnUltimateDebtorCounterpartyMetadataKey   = columnMetadataSpecNamespace + "ultimate_debtor_counterparty"
	ColumnUltimateDebtorCounterpartyIdMetadataKey = columnMetadataSpecNamespace + "ultimate_debtor_counterparty_id"
	ColumnEndToEndIdMetadataKey                   = columnMetadataSpecNamespace + "end_to_end_id"

	ColumnPayoutTypeMetadataKey = columnMetadataSpecNamespace + "payout_type"

	ColumnReasonMetadataKey                            = columnMetadataSpecNamespace + "reason"
	ColumnBicMetadataKey                               = columnMetadataSpecNamespace + "bic"
	ColumnDefaultAccountNumberMetadataKey              = columnMetadataSpecNamespace + "default_account_number"
	ColumnDefaultAccountNumberIDMetadataKey            = columnMetadataSpecNamespace + "default_account_number_id"
	ColumnDescriptionMetadataKey                       = columnMetadataSpecNamespace + "description"
	ColumnIsOverdraftableMetadataKey                   = columnMetadataSpecNamespace + "is_overdraftable"
	ColumnOverdraftReserveAccountIDMetadataKey         = columnMetadataSpecNamespace + "overdraft_reserve_account_id"
	ColumnRoutingNumberMetadataKey                     = columnMetadataSpecNamespace + "routing_number"
	ColumnTypeMetadataKey                              = columnMetadataSpecNamespace + "type"
	ColumnOwnersMetadataKey                            = columnMetadataSpecNamespace + "owners"
	ColumnAccountNumberMetadataKey                     = columnMetadataSpecNamespace + "account_number"
	ColumnAccountTypeMetadataKey                       = columnMetadataSpecNamespace + "account_type"
	ColumnAddressCityMetadataKey                       = columnMetadataSpecNamespace + "address_city"
	ColumnAddressCountryCodeMetadataKey                = columnMetadataSpecNamespace + "address_country_code"
	ColumnAddressLine1MetadataKey                      = columnMetadataSpecNamespace + "address_line1"
	ColumnAddressLine2MetadataKey                      = columnMetadataSpecNamespace + "address_line2"
	ColumnAddressPostalCodeMetadataKey                 = columnMetadataSpecNamespace + "address_postal_code"
	ColumnAddressStateMetadataKey                      = columnMetadataSpecNamespace + "address_state"
	ColumnDisplayNameMetadataKey                       = columnMetadataSpecNamespace + "display_name"
	ColumnEmailMetadataKey                             = columnMetadataSpecNamespace + "email"
	ColumnIsColumnAccountMetadataKey                   = columnMetadataSpecNamespace + "is_column_account"
	ColumnLegalIDMetadataKey                           = columnMetadataSpecNamespace + "legal_id"
	ColumnLegalTypeMetadataKey                         = columnMetadataSpecNamespace + "legal_type"
	ColumnLocalAccountNumberMetadataKey                = columnMetadataSpecNamespace + "local_account_number"
	ColumnLocalBankCodeMetadataKey                     = columnMetadataSpecNamespace + "local_bank_code"
	ColumnLocalBankCountryCodeMetadataKey              = columnMetadataSpecNamespace + "local_bank_country_code"
	ColumnLocalBankNameMetadataKey                     = columnMetadataSpecNamespace + "local_bank_name"
	ColumnNameMetadataKey                              = columnMetadataSpecNamespace + "name"
	ColumnPhoneMetadataKey                             = columnMetadataSpecNamespace + "phone"
	ColumnRoutingNumberTypeMetadataKey                 = columnMetadataSpecNamespace + "routing_number_type"
	ColumnWireDrawdownAllowedMetadataKey               = columnMetadataSpecNamespace + "wire_drawdown_allowed"
	ColumnUpdatedAtMetadataKey                         = columnMetadataSpecNamespace + "updated_at"
	ColumnCompletedAtMetadataKey                       = columnMetadataSpecNamespace + "completed_at"
	ColumnIsIncomingMetadataKey                        = columnMetadataSpecNamespace + "is_incoming"
	ColumnIdempotencyKeyMetadataKey                    = columnMetadataSpecNamespace + "idempotency_key"
	ColumnSenderInternalAccountBankIDMetadataKey       = columnMetadataSpecNamespace + "sender_internal_account_bank_id"
	ColumnSenderInternalAccountNumberIDMetadataKey     = columnMetadataSpecNamespace + "sender_internal_account_number_id"
	ColumnExternalSourceBankNameMetadataKey            = columnMetadataSpecNamespace + "external_source_bank_name"
	ColumnExternalSourceSenderNameMetadataKey          = columnMetadataSpecNamespace + "external_source_sender_name"
	ColumnExternalSourceCounterpartyIDMetadataKey      = columnMetadataSpecNamespace + "external_source_counterparty_id"
	ColumnReceiverInternalAccountBankIDMetadataKey     = columnMetadataSpecNamespace + "receiver_internal_account_bank_id"
	ColumnReceiverInternalAccountNumberIDMetadataKey   = columnMetadataSpecNamespace + "receiver_internal_account_number_id"
	ColumnExternalDestinationCounterpartyIDMetadataKey = columnMetadataSpecNamespace + "external_destination_counterparty_id"

	ColumnEffectiveDateMetadataKey                     = columnMetadataSpecNamespace + "effective_date"
	ColumnSameDayMetadataKey                           = columnMetadataSpecNamespace + "same_day"
	ColumnCompanyDiscretionaryDataMetadataKey          = columnMetadataSpecNamespace + "company_discretionary_data"
	ColumnCompanyEntryDescriptionMetadataKey           = columnMetadataSpecNamespace + "company_entry_description"
	ColumnCompanyNameMetadataKey                       = columnMetadataSpecNamespace + "company_name"
	ColumnPaymentRelatedInfoMetadataKey                = columnMetadataSpecNamespace + "payment_related_info"
	ColumnReceiverNameMetadataKey                      = columnMetadataSpecNamespace + "receiver_name"
	ColumnReceiverIDMetadataKey                        = columnMetadataSpecNamespace + "receiver_id"
	ColumnEntryClassCodeMetadataKey                    = columnMetadataSpecNamespace + "entry_class_code"
	ColumnUltimateOriginatorCounterpartyMetadataKey    = columnMetadataSpecNamespace + "ultimate_originator_counterparty"
	ColumnUltimateOriginatorCounterpartyIDMetadataKey  = columnMetadataSpecNamespace + "ultimate_originator_counterparty_id"
	ColumnUltimateBeneficiaryCounterpartyMetadataKey   = columnMetadataSpecNamespace + "ultimate_beneficiary_counterparty"
	ColumnUltimateBeneficiaryCounterpartyIDMetadataKey = columnMetadataSpecNamespace + "ultimate_beneficiary_counterparty_id"
	ColumnDetailsMetadataKey                           = columnMetadataSpecNamespace + "details"
	ColumnSenderTypeMetadataKey                        = columnMetadataSpecNamespace + "sender_type" // can only be "account_number_id" or "bank_account_id"

	ColumnIsOnUsMetadataKey                          = columnMetadataSpecNamespace + "is_on_us"
	ColumnCompanyIDMetadataKey                       = columnMetadataSpecNamespace + "company_id"
	ColumnSettledAtMetadataKey                       = columnMetadataSpecNamespace + "settled_at"
	ColumnReturnedAtMetadataKey                      = columnMetadataSpecNamespace + "returned_at"
	ColumnCancelledAtMetadataKey                     = columnMetadataSpecNamespace + "cancelled_at"
	ColumnInitiatedAtMetadataKey                     = columnMetadataSpecNamespace + "initiated_at"
	ColumnNSFDeadlineMetadataKey                     = columnMetadataSpecNamespace + "nsf_deadline"
	ColumnSubmittedAtMetadataKey                     = columnMetadataSpecNamespace + "submitted_at"
	ColumnTraceNumberMetadataKey                     = columnMetadataSpecNamespace + "trace_number"
	ColumnAcknowledgedAtMetadataKey                  = columnMetadataSpecNamespace + "acknowledged_at"
	ColumnManualReviewAtMetadataKey                  = columnMetadataSpecNamespace + "manual_review_at"
	ColumnAccountNumberIDMetadataKey                 = columnMetadataSpecNamespace + "account_number_id"
	ColumnFundsAvailabilityMetadataKey               = columnMetadataSpecNamespace + "funds_availability"
	ColumnODFIRoutingNumberMetadataKey               = columnMetadataSpecNamespace + "odfi_routing_number"
	ColumnReturnContestedAtMetadataKey               = columnMetadataSpecNamespace + "return_contested_at"
	ColumnReturnDishonoredAtMetadataKey              = columnMetadataSpecNamespace + "return_dishonored_at"
	ColumnReturnDishonoredFundsUnlockedAtMetadataKey = columnMetadataSpecNamespace + "return_dishonored_funds_unlocked_at"
	ColumnReversalPairTransferIDMetadataKey          = columnMetadataSpecNamespace + "reversal_pair_transfer_id"
	ColumnIATMetadataKey                             = columnMetadataSpecNamespace + "iat"

	ColumnPendingSubmissionAtMetadataKey   = columnMetadataSpecNamespace + "pending_submission_at"
	ColumnRejectedAtMetadataKey            = columnMetadataSpecNamespace + "rejected_at"
	ColumnPlatformIDMetadataKey            = columnMetadataSpecNamespace + "platform_id"
	ColumnWireDrawdownRequestIDMetadataKey = columnMetadataSpecNamespace + "wire_drawdown_request_id"

	ColumnAcceptedAtMetadataKey               = columnMetadataSpecNamespace + "accepted_at"
	ColumnBlockedAtMetadataKey                = columnMetadataSpecNamespace + "blocked_at"
	ColumnManualReviewApprovedAtMetadataKey   = columnMetadataSpecNamespace + "manual_review_approved_at"
	ColumnManualReviewRejectedAtMetadataKey   = columnMetadataSpecNamespace + "manual_review_rejected_at"
	ColumnPendingAtMetadataKey                = columnMetadataSpecNamespace + "pending_at"
	ColumnRejectedCodeMetadataKey             = columnMetadataSpecNamespace + "rejected_code"
	ColumnRejectionCodeDescriptionMetadataKey = columnMetadataSpecNamespace + "rejection_code_description"
	ColumnRejectionAdditionalInfoMetadataKey  = columnMetadataSpecNamespace + "rejection_additional_info"
	ColumnReturnPairTransferIDMetadataKey     = columnMetadataSpecNamespace + "return_pair_transfer_id"

	ColumnRawMessageMetadataKey                 = columnMetadataSpecNamespace + "raw_message"
	ColumnReturnReasonMetadataKey               = columnMetadataSpecNamespace + "return_reason"
	ColumnReturnedAmountMetadataKey             = columnMetadataSpecNamespace + "returned_amount"
	ColumnReturnedCurrencyCodeMetadataKey       = columnMetadataSpecNamespace + "returned_currency_code"
	ColumnSettlementDateMetadataKey             = columnMetadataSpecNamespace + "settlement_date"
	ColumnUETRMetadataKey                       = columnMetadataSpecNamespace + "uetr"
	ColumnInstructionIDMetadataKey              = columnMetadataSpecNamespace + "instruction_id"
	ColumnEndToEndIDMetadataKey                 = columnMetadataSpecNamespace + "end_to_end_id"
	ColumnFXQuoteIDMetadataKey                  = columnMetadataSpecNamespace + "fx_quote_id"
	ColumnFXRateMetadataKey                     = columnMetadataSpecNamespace + "fx_rate"
	ColumnInstructedAmountMetadataKey           = columnMetadataSpecNamespace + "instructed_amount"
	ColumnInstructedCurrencyCodeMetadataKey     = columnMetadataSpecNamespace + "instructed_currency_code"
	ColumnSettledAmountMetadataKey              = columnMetadataSpecNamespace + "settled_amount"
	ColumnSettledCurrencyCodeMetadataKey        = columnMetadataSpecNamespace + "settled_currency_code"
	ColumnInstructionToBeneficiaryFIMetadataKey = columnMetadataSpecNamespace + "instruction_to_beneficiary_fi"
	ColumnBeneficiaryAccountNumberMetadataKey   = columnMetadataSpecNamespace + "beneficiary_account_number"
	ColumnBeneficiaryFIMetadataKey              = columnMetadataSpecNamespace + "beneficiary_fi"
	ColumnBeneficiaryNameMetadataKey            = columnMetadataSpecNamespace + "beneficiary_name"
	ColumnOriginatorAccountNumberMetadataKey    = columnMetadataSpecNamespace + "originator_account_number"
	ColumnOriginatorFIMetadataKey               = columnMetadataSpecNamespace + "originator_fi"
	ColumnOriginatorNameMetadataKey             = columnMetadataSpecNamespace + "originator_name"
	ColumnUltimateBeneficiaryNameMetadataKey    = columnMetadataSpecNamespace + "ultimate_beneficiary_name"
	ColumnUltimateOriginatorNameMetadataKey     = columnMetadataSpecNamespace + "ultimate_originator_name"
	ColumnChargesMetadataKey                    = columnMetadataSpecNamespace + "charges"
	ColumnBeneficiaryAddressMetadataKey         = columnMetadataSpecNamespace + "beneficiary_address"
	ColumnOriginatorAddressMetadataKey          = columnMetadataSpecNamespace + "originator_address"
	ColumnUltimateBeneficiaryAddressMetadataKey = columnMetadataSpecNamespace + "ultimate_beneficiary_address"
	ColumnUltimateOriginatorAddressMetadataKey  = columnMetadataSpecNamespace + "ultimate_originator_address"
	ColumnRemittanceInfoMetadataKey             = columnMetadataSpecNamespace + "remittance_info"

	ColumnSenderBankAccountIDMetadataKey   = columnMetadataSpecNamespace + "sender_bank_account_id"
	ColumnReceiverBankAccountIDMetadataKey = columnMetadataSpecNamespace + "receiver_bank_account_id"
)
