package client

const (
	columnMetadataSpecNamespace = "com.column.spec/"

	ColumnCityMetadataKey        = columnMetadataSpecNamespace + "city"
	ColumnStateMetadataKey       = columnMetadataSpecNamespace + "state"
	ColumnPostalCodeMetadataKey  = columnMetadataSpecNamespace + "postal_code"
	ColumnCountryCodeMetadataKey = columnMetadataSpecNamespace + "country_code"

	ColumnSenderAccountNumberIdMetadataKey = columnMetadataSpecNamespace + "sender_account_number_id"

	ColumnReceiverAccountNumberIdMetadataKey = columnMetadataSpecNamespace + "receiver_account_number_id"

	ColumnMerchantNameMetadataKey         = columnMetadataSpecNamespace + "merchant_name"
	ColumnMerchantCategoryCodeMetadataKey = columnMetadataSpecNamespace + "merchant_category_code"
	ColumnAuthorizationMethodMetadataKey  = columnMetadataSpecNamespace + "authorization_method"
	ColumnInternalTransferTypeMetadataKey = columnMetadataSpecNamespace + "internal_transfer_type"
	ColumnWebsiteMetadataKey              = columnMetadataSpecNamespace + "website"

	ColumnAllowOverdraftMetadataKey = columnMetadataSpecNamespace + "allow_overdraft"
	ColumnHoldMetadataKey           = columnMetadataSpecNamespace + "hold"

	ColumnAmountConditionMetadataKey = columnMetadataSpecNamespace + "amount_condition"

	ColumnUltimateOriginatorCounterpartyIdMetadataKey = columnMetadataSpecNamespace + "ultimate_originator_counterparty_id"
	ColumnUltimateOriginatorAccountNumberMetadataKey  = columnMetadataSpecNamespace + "ultimate_originator_account_number"
	ColumnChargeBearerMetadataKey                     = columnMetadataSpecNamespace + "charge_bearer"
	ColumnFxQuoteIdMetadataKey                        = columnMetadataSpecNamespace + "fx_quote_id"
	ColumnIntermediaryBankMetadataKey                 = columnMetadataSpecNamespace + "intermediary_bank"
	ColumnMessageToBeneficiaryBankMetadataKey         = columnMetadataSpecNamespace + "message_to_beneficiary_bank"
	ColumnGeneralInfoMetadataKey                      = columnMetadataSpecNamespace + "general_info"
	ColumnBeneficiaryReferenceMetadataKey             = columnMetadataSpecNamespace + "beneficiary_reference"
	ColumnPurposeCodeMetadataKey                      = columnMetadataSpecNamespace + "purpose_code"

	ColumnUltimateDebtorCounterpartyMetadataKey   = columnMetadataSpecNamespace + "ultimate_debtor_counterparty"
	ColumnUltimateDebtorCounterpartyIdMetadataKey = columnMetadataSpecNamespace + "ultimate_debtor_counterparty_id"
	ColumnEndToEndIdMetadataKey                   = columnMetadataSpecNamespace + "end_to_end_id"

	ColumnPayoutTypeMetadataKey = columnMetadataSpecNamespace + "payout_type"

	ColumnAchTransferIDMetadataKey                     = columnMetadataSpecNamespace + "ach_transfer_id"
	ColumnReasonMetadataKey                            = columnMetadataSpecNamespace + "reason"
	ColumnBicMetadataKey                               = columnMetadataSpecNamespace + "bic"
	ColumnDefaultAccountNumberMetadataKey              = columnMetadataSpecNamespace + "default_account_number"
	ColumnDefaultAccountNumberIDMetadataKey            = columnMetadataSpecNamespace + "default_account_number_id"
	ColumnDescriptionMetadataKey                       = columnMetadataSpecNamespace + "description"
	ColumnIsOverdraftableMetadataKey                   = columnMetadataSpecNamespace + "is_overdraftable"
	ColumnOverdraftReserveAccountIDMetadataKey         = columnMetadataSpecNamespace + "overdraft_reserve_account_id"
	ColumnRoutingNumberMetadataKey                     = columnMetadataSpecNamespace + "routing_number"
	ColumnTypeMetadataKey                              = columnMetadataSpecNamespace + "type"
	ColumnOwnersMetadataKey                            = columnMetadataSpecNamespace + "owners"
	ColumnAccountNumberMetadataKey                     = columnMetadataSpecNamespace + "account_number"
	ColumnAccountTypeMetadataKey                       = columnMetadataSpecNamespace + "account_type"
	ColumnAddressCityMetadataKey                       = columnMetadataSpecNamespace + "address_city"
	ColumnAddressCountryCodeMetadataKey                = columnMetadataSpecNamespace + "address_country_code"
	ColumnAddressLine1MetadataKey                      = columnMetadataSpecNamespace + "address_line1"
	ColumnAddressLine2MetadataKey                      = columnMetadataSpecNamespace + "address_line2"
	ColumnAddressPostalCodeMetadataKey                 = columnMetadataSpecNamespace + "address_postal_code"
	ColumnAddressStateMetadataKey                      = columnMetadataSpecNamespace + "address_state"
	ColumnDisplayNameMetadataKey                       = columnMetadataSpecNamespace + "display_name"
	ColumnEmailMetadataKey                             = columnMetadataSpecNamespace + "email"
	ColumnIsColumnAccountMetadataKey                   = columnMetadataSpecNamespace + "is_column_account"
	ColumnLegalIDMetadataKey                           = columnMetadataSpecNamespace + "legal_id"
	ColumnLegalTypeMetadataKey                         = columnMetadataSpecNamespace + "legal_type"
	ColumnLocalAccountNumberMetadataKey                = columnMetadataSpecNamespace + "local_account_number"
	ColumnLocalBankCodeMetadataKey                     = columnMetadataSpecNamespace + "local_bank_code"
	ColumnLocalBankCountryCodeMetadataKey              = columnMetadataSpecNamespace + "local_bank_country_code"
	ColumnLocalBankNameMetadataKey                     = columnMetadataSpecNamespace + "local_bank_name"
	ColumnNameMetadataKey                              = columnMetadataSpecNamespace + "name"
	ColumnPhoneMetadataKey                             = columnMetadataSpecNamespace + "phone"
	ColumnRoutingNumberTypeMetadataKey                 = columnMetadataSpecNamespace + "routing_number_type"
	ColumnWireDrawdownAllowedMetadataKey               = columnMetadataSpecNamespace + "wire_drawdown_allowed"
	ColumnUpdatedAtMetadataKey                         = columnMetadataSpecNamespace + "updated_at"
	ColumnCompletedAtMetadataKey                       = columnMetadataSpecNamespace + "completed_at"
	ColumnIsIncomingMetadataKey                        = columnMetadataSpecNamespace + "is_incoming"
	ColumnIdempotencyKeyMetadataKey                    = columnMetadataSpecNamespace + "idempotency_key"
	ColumnSenderInternalAccountBankIDMetadataKey       = columnMetadataSpecNamespace + "sender_internal_account_bank_id"
	ColumnSenderInternalAccountNumberIDMetadataKey     = columnMetadataSpecNamespace + "sender_internal_account_number_id"
	ColumnExternalSourceBankNameMetadataKey            = columnMetadataSpecNamespace + "external_source_bank_name"
	ColumnExternalSourceSenderNameMetadataKey          = columnMetadataSpecNamespace + "external_source_sender_name"
	ColumnExternalSourceCounterpartyIDMetadataKey      = columnMetadataSpecNamespace + "external_source_counterparty_id"
	ColumnReceiverInternalAccountBankIDMetadataKey     = columnMetadataSpecNamespace + "receiver_internal_account_bank_id"
	ColumnReceiverInternalAccountNumberIDMetadataKey   = columnMetadataSpecNamespace + "receiver_internal_account_number_id"
	ColumnExternalDestinationCounterpartyIDMetadataKey = columnMetadataSpecNamespace + "external_destination_counterparty_id"

	ColumnSenderTypeMetadataKey = columnMetadataSpecNamespace + "sender_type" // can only be "account_number_id" or "bank_account_id"
)
