components:
    schemas:
        V3ConnectorConfig:
            discriminator:
                propertyName: provider
                mapping:
                    Adyen: '#/components/schemas/V3AdyenConfig'
                    Atlar: '#/components/schemas/V3AtlarConfig'
                    Bankingcircle: '#/components/schemas/V3BankingcircleConfig'
                    Column: '#/components/schemas/V3ColumnConfig'
                    Currencycloud: '#/components/schemas/V3CurrencycloudConfig'
                    Dummypay: '#/components/schemas/V3DummypayConfig'
                    Generic: '#/components/schemas/V3GenericConfig'
                    Increase: '#/components/schemas/V3IncreaseConfig'
                    Mangopay: '#/components/schemas/V3MangopayConfig'
                    Modulr: '#/components/schemas/V3ModulrConfig'
                    Moneycorp: '#/components/schemas/V3MoneycorpConfig'
                    Plaid: '#/components/schemas/V3PlaidConfig'
                    Powens: '#/components/schemas/V3PowensConfig'
                    Qonto: '#/components/schemas/V3QontoConfig'
                    Stripe: '#/components/schemas/V3StripeConfig'
                    Tink: '#/components/schemas/V3TinkConfig'
                    Wise: '#/components/schemas/V3WiseConfig'
            oneOf:
                - $ref: '#/components/schemas/V3AdyenConfig'
                - $ref: '#/components/schemas/V3AtlarConfig'
                - $ref: '#/components/schemas/V3BankingcircleConfig'
                - $ref: '#/components/schemas/V3ColumnConfig'
                - $ref: '#/components/schemas/V3CurrencycloudConfig'
                - $ref: '#/components/schemas/V3DummypayConfig'
                - $ref: '#/components/schemas/V3GenericConfig'
                - $ref: '#/components/schemas/V3IncreaseConfig'
                - $ref: '#/components/schemas/V3MangopayConfig'
                - $ref: '#/components/schemas/V3ModulrConfig'
                - $ref: '#/components/schemas/V3MoneycorpConfig'
                - $ref: '#/components/schemas/V3PlaidConfig'
                - $ref: '#/components/schemas/V3PowensConfig'
                - $ref: '#/components/schemas/V3QontoConfig'
                - $ref: '#/components/schemas/V3StripeConfig'
                - $ref: '#/components/schemas/V3TinkConfig'
                - $ref: '#/components/schemas/V3WiseConfig'
        V3AdyenConfig:
            type: object
            required:
                - name
                - apiKey
                - companyID
            properties:
                apiKey:
                    type: string
                companyID:
                    type: string
                liveEndpointPrefix:
                    type: string
                name:
                    type: string
                pageSize:
                    type: integer
                    default: 25
                pollingPeriod:
                    type: string
                    default: 2m
                provider:
                    type: string
                    default: Adyen
                webhookPassword:
                    type: string
                webhookUsername:
                    type: string
        V3AtlarConfig:
            type: object
            required:
                - name
                - baseUrl
                - accessKey
                - secret
            properties:
                accessKey:
                    type: string
                baseUrl:
                    type: string
                name:
                    type: string
                pageSize:
                    type: integer
                    default: 25
                pollingPeriod:
                    type: string
                    default: 2m
                provider:
                    type: string
                    default: Atlar
                secret:
                    type: string
        V3BankingcircleConfig:
            type: object
            required:
                - name
                - username
                - password
                - endpoint
                - authorizationEndpoint
                - userCertificate
                - userCertificateKey
            properties:
                authorizationEndpoint:
                    type: string
                endpoint:
                    type: string
                name:
                    type: string
                pageSize:
                    type: integer
                    default: 25
                password:
                    type: string
                pollingPeriod:
                    type: string
                    default: 2m
                provider:
                    type: string
                    default: Bankingcircle
                userCertificate:
                    type: string
                userCertificateKey:
                    type: string
                username:
                    type: string
        V3ColumnConfig:
            type: object
            required:
                - name
                - apiKey
                - endpoint
            properties:
                apiKey:
                    type: string
                endpoint:
                    type: string
                name:
                    type: string
                pageSize:
                    type: integer
                    default: 25
                pollingPeriod:
                    type: string
                    default: 2m
                provider:
                    type: string
                    default: Column
        V3CurrencycloudConfig:
            type: object
            required:
                - name
                - loginID
                - apiKey
                - endpoint
            properties:
                apiKey:
                    type: string
                endpoint:
                    type: string
                loginID:
                    type: string
                name:
                    type: string
                pageSize:
                    type: integer
                    default: 25
                pollingPeriod:
                    type: string
                    default: 2m
                provider:
                    type: string
                    default: Currencycloud
        V3DummypayConfig:
            type: object
            required:
                - name
                - directory
            properties:
                directory:
                    type: string
                linkFlowError:
                    type: boolean
                name:
                    type: string
                pageSize:
                    type: integer
                    default: 25
                pollingPeriod:
                    type: string
                    default: 2m
                provider:
                    type: string
                    default: Dummypay
                updateLinkFlowError:
                    type: boolean
        V3GenericConfig:
            type: object
            required:
                - name
                - apiKey
                - endpoint
            properties:
                apiKey:
                    type: string
                endpoint:
                    type: string
                name:
                    type: string
                pageSize:
                    type: integer
                    default: 25
                pollingPeriod:
                    type: string
                    default: 2m
                provider:
                    type: string
                    default: Generic
        V3IncreaseConfig:
            type: object
            required:
                - name
                - apiKey
                - endpoint
                - webhookSharedSecret
            properties:
                apiKey:
                    type: string
                endpoint:
                    type: string
                name:
                    type: string
                pageSize:
                    type: integer
                    default: 25
                pollingPeriod:
                    type: string
                    default: 2m
                provider:
                    type: string
                    default: Increase
                webhookSharedSecret:
                    type: string
        V3MangopayConfig:
            type: object
            required:
                - name
                - clientID
                - apiKey
                - endpoint
            properties:
                apiKey:
                    type: string
                clientID:
                    type: string
                endpoint:
                    type: string
                name:
                    type: string
                pageSize:
                    type: integer
                    default: 25
                pollingPeriod:
                    type: string
                    default: 2m
                provider:
                    type: string
                    default: Mangopay
        V3ModulrConfig:
            type: object
            required:
                - name
                - apiKey
                - apiSecret
                - endpoint
            properties:
                apiKey:
                    type: string
                apiSecret:
                    type: string
                endpoint:
                    type: string
                name:
                    type: string
                pageSize:
                    type: integer
                    default: 25
                pollingPeriod:
                    type: string
                    default: 2m
                provider:
                    type: string
                    default: Modulr
        V3MoneycorpConfig:
            type: object
            required:
                - name
                - clientID
                - apiKey
                - endpoint
            properties:
                apiKey:
                    type: string
                clientID:
                    type: string
                endpoint:
                    type: string
                name:
                    type: string
                pageSize:
                    type: integer
                    default: 25
                pollingPeriod:
                    type: string
                    default: 2m
                provider:
                    type: string
                    default: Moneycorp
        V3PlaidConfig:
            type: object
            required:
                - name
                - clientID
                - clientSecret
            properties:
                clientID:
                    type: string
                clientSecret:
                    type: string
                isSandbox:
                    type: boolean
                name:
                    type: string
                pageSize:
                    type: integer
                    default: 25
                pollingPeriod:
                    type: string
                    default: 2m
                provider:
                    type: string
                    default: Plaid
        V3PowensConfig:
            type: object
            required:
                - name
                - clientID
                - clientSecret
                - configurationToken
                - domain
                - maxConnectionsPerLink
                - endpoint
            properties:
                clientID:
                    type: string
                clientSecret:
                    type: string
                configurationToken:
                    type: string
                domain:
                    type: string
                endpoint:
                    type: string
                maxConnectionsPerLink:
                    type: integer
                name:
                    type: string
                pageSize:
                    type: integer
                    default: 25
                pollingPeriod:
                    type: string
                    default: 2m
                provider:
                    type: string
                    default: Powens
        V3QontoConfig:
            type: object
            required:
                - name
                - clientID
                - apiKey
                - endpoint
            properties:
                apiKey:
                    type: string
                clientID:
                    type: string
                endpoint:
                    type: string
                name:
                    type: string
                pageSize:
                    type: integer
                    default: 25
                pollingPeriod:
                    type: string
                    default: 2m
                provider:
                    type: string
                    default: Qonto
                stagingToken:
                    type: string
        V3StripeConfig:
            type: object
            required:
                - name
                - apiKey
            properties:
                apiKey:
                    type: string
                name:
                    type: string
                pageSize:
                    type: integer
                    default: 25
                pollingPeriod:
                    type: string
                provider:
                    type: string
                    default: Stripe
        V3TinkConfig:
            type: object
            required:
                - name
                - clientID
                - clientSecret
                - endpoint
            properties:
                clientID:
                    type: string
                clientSecret:
                    type: string
                endpoint:
                    type: string
                name:
                    type: string
                pageSize:
                    type: integer
                    default: 25
                pollingPeriod:
                    type: string
                    default: 2m
                provider:
                    type: string
                    default: Tink
        V3WiseConfig:
            type: object
            required:
                - name
                - apiKey
                - webhookPublicKey
            properties:
                apiKey:
                    type: string
                name:
                    type: string
                pageSize:
                    type: integer
                    default: 25
                pollingPeriod:
                    type: string
                    default: 2m
                provider:
                    type: string
                    default: Wise
                webhookPublicKey:
                    type: string
