// Code generated by MockGen. DO NOT EDIT.
// Source: webhooks.go
//
// Generated by this command:
//
//	mockgen -source webhooks.go -destination webhookverifier_generated.go -package increase WebhookVerifier
//

// Package increase is a generated GoMock package.
package increase

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWebhookVerifier is a mock of WebhookVerifier interface.
type MockWebhookVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookVerifierMockRecorder
	isgomock struct{}
}

// MockWebhookVerifierMockRecorder is the mock recorder for MockWebhookVerifier.
type MockWebhookVerifierMockRecorder struct {
	mock *MockWebhookVerifier
}

// NewMockWebhookVerifier creates a new mock instance.
func NewMockWebhookVerifier(ctrl *gomock.Controller) *MockWebhookVerifier {
	mock := &MockWebhookVerifier{ctrl: ctrl}
	mock.recorder = &MockWebhookVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookVerifier) EXPECT() *MockWebhookVerifierMockRecorder {
	return m.recorder
}

// verifyWebhookSignature mocks base method.
func (m *MockWebhookVerifier) verifyWebhookSignature(payload []byte, header string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "verifyWebhookSignature", payload, header)
	ret0, _ := ret[0].(error)
	return ret0
}

// verifyWebhookSignature indicates an expected call of verifyWebhookSignature.
func (mr *MockWebhookVerifierMockRecorder) verifyWebhookSignature(payload, header any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "verifyWebhookSignature", reflect.TypeOf((*MockWebhookVerifier)(nil).verifyWebhookSignature), payload, header)
}
