// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source client.go -destination client_generated.go -package client . Client
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetAccountBalances mocks base method.
func (m *MockClient) GetAccountBalances(ctx context.Context) ([]AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountBalances", ctx)
	ret0, _ := ret[0].([]AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountBalances indicates an expected call of GetAccountBalances.
func (mr *MockClientMockRecorder) GetAccountBalances(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountBalances", reflect.TypeOf((*MockClient)(nil).GetAccountBalances), ctx)
}

// GetCurrencies mocks base method.
func (m *MockClient) GetCurrencies(ctx context.Context) ([]Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrencies", ctx)
	ret0, _ := ret[0].([]Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrencies indicates an expected call of GetCurrencies.
func (mr *MockClientMockRecorder) GetCurrencies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrencies", reflect.TypeOf((*MockClient)(nil).GetCurrencies), ctx)
}

// GetOpenOrders mocks base method.
func (m *MockClient) GetOpenOrders(ctx context.Context) ([]OpenOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenOrders", ctx)
	ret0, _ := ret[0].([]OpenOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenOrders indicates an expected call of GetOpenOrders.
func (mr *MockClientMockRecorder) GetOpenOrders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenOrders", reflect.TypeOf((*MockClient)(nil).GetOpenOrders), ctx)
}

// GetOpenOrdersForMarket mocks base method.
func (m *MockClient) GetOpenOrdersForMarket(ctx context.Context, currencyPair string) ([]OpenOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenOrdersForMarket", ctx, currencyPair)
	ret0, _ := ret[0].([]OpenOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenOrdersForMarket indicates an expected call of GetOpenOrdersForMarket.
func (mr *MockClientMockRecorder) GetOpenOrdersForMarket(ctx, currencyPair any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenOrdersForMarket", reflect.TypeOf((*MockClient)(nil).GetOpenOrdersForMarket), ctx, currencyPair)
}

// GetOrderStatus mocks base method.
func (m *MockClient) GetOrderStatus(ctx context.Context, orderID string) (OrderStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderStatus", ctx, orderID)
	ret0, _ := ret[0].(OrderStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderStatus indicates an expected call of GetOrderStatus.
func (mr *MockClientMockRecorder) GetOrderStatus(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderStatus", reflect.TypeOf((*MockClient)(nil).GetOrderStatus), ctx, orderID)
}

// GetUserTransactions mocks base method.
func (m *MockClient) GetUserTransactions(ctx context.Context, sinceID *int64, limit int) ([]UserTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTransactions", ctx, sinceID, limit)
	ret0, _ := ret[0].([]UserTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTransactions indicates an expected call of GetUserTransactions.
func (mr *MockClientMockRecorder) GetUserTransactions(ctx, sinceID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTransactions", reflect.TypeOf((*MockClient)(nil).GetUserTransactions), ctx, sinceID, limit)
}
