serviceName: search
env: prod
awsAccountId: "288350113309"

replicaCount: 2
hpaMinReplicas: 2
hpaMaxReplicas: 200

image:
  repository: dkr.ecr.eu-west-1.amazonaws.com/numary
  tag: payments-main

resource:
  ephemeral: false
  hpa: true

ephemeralName: ""

global:
  exposeUrl: "api.prod.numary.cloud"
  auth: https://api.numary.cloud/auth
  mongodbUri: "mongodb://mongodb:27017"
  mongodbDatabase: "payments"