/*
Sample API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymentclient

import (
	"encoding/json"
)

// PaymentValue struct for PaymentValue
type PaymentValue struct {
	Amount int32 `json:"amount"`
	Asset string `json:"asset"`
}

// NewPaymentValue instantiates a new PaymentValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentValue(amount int32, asset string) *PaymentValue {
	this := PaymentValue{}
	this.Amount = amount
	this.Asset = asset
	return &this
}

// NewPaymentValueWithDefaults instantiates a new PaymentValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentValueWithDefaults() *PaymentValue {
	this := PaymentValue{}
	return &this
}

// GetAmount returns the Amount field value
func (o *PaymentValue) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *PaymentValue) GetAmountOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *PaymentValue) SetAmount(v int32) {
	o.Amount = v
}

// GetAsset returns the Asset field value
func (o *PaymentValue) GetAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *PaymentValue) GetAssetOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *PaymentValue) SetAsset(v string) {
	o.Asset = v
}

func (o PaymentValue) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["amount"] = o.Amount
	}
	if true {
		toSerialize["asset"] = o.Asset
	}
	return json.Marshal(toSerialize)
}

type NullablePaymentValue struct {
	value *PaymentValue
	isSet bool
}

func (v NullablePaymentValue) Get() *PaymentValue {
	return v.value
}

func (v *NullablePaymentValue) Set(val *PaymentValue) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentValue) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentValue(val *PaymentValue) *NullablePaymentValue {
	return &NullablePaymentValue{value: val, isSet: true}
}

func (v NullablePaymentValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


