// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source client.go -destination client_generated.go -package client . Client
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateBankAccount mocks base method.
func (m *MockClient) CreateBankAccount(ctx context.Context, pr *BankAccountRequest) (*BankAccountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBankAccount", ctx, pr)
	ret0, _ := ret[0].(*BankAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBankAccount indicates an expected call of CreateBankAccount.
func (mr *MockClientMockRecorder) CreateBankAccount(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBankAccount", reflect.TypeOf((*MockClient)(nil).CreateBankAccount), ctx, pr)
}

// GetAccount mocks base method.
func (m *MockClient) GetAccount(ctx context.Context, accountID string) (*Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, accountID)
	ret0, _ := ret[0].(*Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockClientMockRecorder) GetAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockClient)(nil).GetAccount), ctx, accountID)
}

// GetAccountBalance mocks base method.
func (m *MockClient) GetAccountBalance(ctx context.Context, accountID string) (*Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountBalance", ctx, accountID)
	ret0, _ := ret[0].(*Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountBalance indicates an expected call of GetAccountBalance.
func (mr *MockClientMockRecorder) GetAccountBalance(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountBalance", reflect.TypeOf((*MockClient)(nil).GetAccountBalance), ctx, accountID)
}

// GetAccounts mocks base method.
func (m *MockClient) GetAccounts(ctx context.Context, pageSize int, cursor string) ([]*Account, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccounts", ctx, pageSize, cursor)
	ret0, _ := ret[0].([]*Account)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAccounts indicates an expected call of GetAccounts.
func (mr *MockClientMockRecorder) GetAccounts(ctx, pageSize, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccounts", reflect.TypeOf((*MockClient)(nil).GetAccounts), ctx, pageSize, cursor)
}

// GetDeclinedTransactions mocks base method.
func (m *MockClient) GetDeclinedTransactions(ctx context.Context, pageSize int, cursor string) ([]*Transaction, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeclinedTransactions", ctx, pageSize, cursor)
	ret0, _ := ret[0].([]*Transaction)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeclinedTransactions indicates an expected call of GetDeclinedTransactions.
func (mr *MockClientMockRecorder) GetDeclinedTransactions(ctx, pageSize, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeclinedTransactions", reflect.TypeOf((*MockClient)(nil).GetDeclinedTransactions), ctx, pageSize, cursor)
}

// GetExternalAccounts mocks base method.
func (m *MockClient) GetExternalAccounts(ctx context.Context, pageSize int, cursor string) ([]*ExternalAccount, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalAccounts", ctx, pageSize, cursor)
	ret0, _ := ret[0].([]*ExternalAccount)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetExternalAccounts indicates an expected call of GetExternalAccounts.
func (mr *MockClientMockRecorder) GetExternalAccounts(ctx, pageSize, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalAccounts", reflect.TypeOf((*MockClient)(nil).GetExternalAccounts), ctx, pageSize, cursor)
}

// GetPendingTransactions mocks base method.
func (m *MockClient) GetPendingTransactions(ctx context.Context, pageSize int, cursor string) ([]*Transaction, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingTransactions", ctx, pageSize, cursor)
	ret0, _ := ret[0].([]*Transaction)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPendingTransactions indicates an expected call of GetPendingTransactions.
func (mr *MockClientMockRecorder) GetPendingTransactions(ctx, pageSize, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingTransactions", reflect.TypeOf((*MockClient)(nil).GetPendingTransactions), ctx, pageSize, cursor)
}

// GetTransactions mocks base method.
func (m *MockClient) GetTransactions(ctx context.Context, pageSize int, cursor string) ([]*Transaction, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactions", ctx, pageSize, cursor)
	ret0, _ := ret[0].([]*Transaction)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTransactions indicates an expected call of GetTransactions.
func (mr *MockClientMockRecorder) GetTransactions(ctx, pageSize, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactions", reflect.TypeOf((*MockClient)(nil).GetTransactions), ctx, pageSize, cursor)
}

// InitiateACHTransferPayout mocks base method.
func (m *MockClient) InitiateACHTransferPayout(ctx context.Context, pr *ACHPayoutRequest) (*PayoutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateACHTransferPayout", ctx, pr)
	ret0, _ := ret[0].(*PayoutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateACHTransferPayout indicates an expected call of InitiateACHTransferPayout.
func (mr *MockClientMockRecorder) InitiateACHTransferPayout(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateACHTransferPayout", reflect.TypeOf((*MockClient)(nil).InitiateACHTransferPayout), ctx, pr)
}

// InitiateCheckTransferPayout mocks base method.
func (m *MockClient) InitiateCheckTransferPayout(ctx context.Context, pr *CheckPayoutRequest) (*PayoutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateCheckTransferPayout", ctx, pr)
	ret0, _ := ret[0].(*PayoutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateCheckTransferPayout indicates an expected call of InitiateCheckTransferPayout.
func (mr *MockClientMockRecorder) InitiateCheckTransferPayout(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateCheckTransferPayout", reflect.TypeOf((*MockClient)(nil).InitiateCheckTransferPayout), ctx, pr)
}

// InitiateRTPTransferPayout mocks base method.
func (m *MockClient) InitiateRTPTransferPayout(ctx context.Context, pr *RTPPayoutRequest) (*PayoutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateRTPTransferPayout", ctx, pr)
	ret0, _ := ret[0].(*PayoutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateRTPTransferPayout indicates an expected call of InitiateRTPTransferPayout.
func (mr *MockClientMockRecorder) InitiateRTPTransferPayout(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateRTPTransferPayout", reflect.TypeOf((*MockClient)(nil).InitiateRTPTransferPayout), ctx, pr)
}

// InitiateTransfer mocks base method.
func (m *MockClient) InitiateTransfer(ctx context.Context, tr *TransferRequest) (*TransferResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateTransfer", ctx, tr)
	ret0, _ := ret[0].(*TransferResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateTransfer indicates an expected call of InitiateTransfer.
func (mr *MockClientMockRecorder) InitiateTransfer(ctx, tr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateTransfer", reflect.TypeOf((*MockClient)(nil).InitiateTransfer), ctx, tr)
}

// InitiateWireTransferPayout mocks base method.
func (m *MockClient) InitiateWireTransferPayout(ctx context.Context, pr *WireTransferPayoutRequest) (*PayoutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateWireTransferPayout", ctx, pr)
	ret0, _ := ret[0].(*PayoutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiateWireTransferPayout indicates an expected call of InitiateWireTransferPayout.
func (mr *MockClientMockRecorder) InitiateWireTransferPayout(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateWireTransferPayout", reflect.TypeOf((*MockClient)(nil).InitiateWireTransferPayout), ctx, pr)
}
