// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source client.go -destination client_generated.go -package client . Client
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CancelOrder mocks base method.
func (m *MockClient) CancelOrder(ctx context.Context, orderID string) (*CancelOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", ctx, orderID)
	ret0, _ := ret[0].(*CancelOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockClientMockRecorder) CancelOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockClient)(nil).CancelOrder), ctx, orderID)
}

// CreateLimitBuyOrder mocks base method.
func (m *MockClient) CreateLimitBuyOrder(ctx context.Context, req CreateOrderRequest) (*CreateOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLimitBuyOrder", ctx, req)
	ret0, _ := ret[0].(*CreateOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLimitBuyOrder indicates an expected call of CreateLimitBuyOrder.
func (mr *MockClientMockRecorder) CreateLimitBuyOrder(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLimitBuyOrder", reflect.TypeOf((*MockClient)(nil).CreateLimitBuyOrder), ctx, req)
}

// CreateLimitSellOrder mocks base method.
func (m *MockClient) CreateLimitSellOrder(ctx context.Context, req CreateOrderRequest) (*CreateOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLimitSellOrder", ctx, req)
	ret0, _ := ret[0].(*CreateOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLimitSellOrder indicates an expected call of CreateLimitSellOrder.
func (mr *MockClientMockRecorder) CreateLimitSellOrder(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLimitSellOrder", reflect.TypeOf((*MockClient)(nil).CreateLimitSellOrder), ctx, req)
}

// CreateMarketBuyOrder mocks base method.
func (m *MockClient) CreateMarketBuyOrder(ctx context.Context, req CreateOrderRequest) (*CreateOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMarketBuyOrder", ctx, req)
	ret0, _ := ret[0].(*CreateOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMarketBuyOrder indicates an expected call of CreateMarketBuyOrder.
func (mr *MockClientMockRecorder) CreateMarketBuyOrder(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMarketBuyOrder", reflect.TypeOf((*MockClient)(nil).CreateMarketBuyOrder), ctx, req)
}

// CreateMarketSellOrder mocks base method.
func (m *MockClient) CreateMarketSellOrder(ctx context.Context, req CreateOrderRequest) (*CreateOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMarketSellOrder", ctx, req)
	ret0, _ := ret[0].(*CreateOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMarketSellOrder indicates an expected call of CreateMarketSellOrder.
func (mr *MockClientMockRecorder) CreateMarketSellOrder(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMarketSellOrder", reflect.TypeOf((*MockClient)(nil).CreateMarketSellOrder), ctx, req)
}

// GetBalances mocks base method.
func (m *MockClient) GetBalances(ctx context.Context) ([]AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalances", ctx)
	ret0, _ := ret[0].([]AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalances indicates an expected call of GetBalances.
func (mr *MockClientMockRecorder) GetBalances(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalances", reflect.TypeOf((*MockClient)(nil).GetBalances), ctx)
}

// GetOHLC mocks base method.
func (m *MockClient) GetOHLC(ctx context.Context, market string, step, limit int) (*OHLCResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOHLC", ctx, market, step, limit)
	ret0, _ := ret[0].(*OHLCResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOHLC indicates an expected call of GetOHLC.
func (mr *MockClientMockRecorder) GetOHLC(ctx, market, step, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOHLC", reflect.TypeOf((*MockClient)(nil).GetOHLC), ctx, market, step, limit)
}

// GetOpenOrders mocks base method.
func (m *MockClient) GetOpenOrders(ctx context.Context, market string) ([]Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenOrders", ctx, market)
	ret0, _ := ret[0].([]Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenOrders indicates an expected call of GetOpenOrders.
func (mr *MockClientMockRecorder) GetOpenOrders(ctx, market any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenOrders", reflect.TypeOf((*MockClient)(nil).GetOpenOrders), ctx, market)
}

// GetOrderBook mocks base method.
func (m *MockClient) GetOrderBook(ctx context.Context, market string) (*OrderBookResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderBook", ctx, market)
	ret0, _ := ret[0].(*OrderBookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderBook indicates an expected call of GetOrderBook.
func (mr *MockClientMockRecorder) GetOrderBook(ctx, market any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderBook", reflect.TypeOf((*MockClient)(nil).GetOrderBook), ctx, market)
}

// GetOrderStatus mocks base method.
func (m *MockClient) GetOrderStatus(ctx context.Context, orderID string) (*OrderStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderStatus", ctx, orderID)
	ret0, _ := ret[0].(*OrderStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderStatus indicates an expected call of GetOrderStatus.
func (mr *MockClientMockRecorder) GetOrderStatus(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderStatus", reflect.TypeOf((*MockClient)(nil).GetOrderStatus), ctx, orderID)
}

// GetTicker mocks base method.
func (m *MockClient) GetTicker(ctx context.Context, market string) (*TickerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTicker", ctx, market)
	ret0, _ := ret[0].(*TickerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicker indicates an expected call of GetTicker.
func (mr *MockClientMockRecorder) GetTicker(ctx, market any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicker", reflect.TypeOf((*MockClient)(nil).GetTicker), ctx, market)
}

// GetTradingPairs mocks base method.
func (m *MockClient) GetTradingPairs(ctx context.Context) ([]TradingPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTradingPairs", ctx)
	ret0, _ := ret[0].([]TradingPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTradingPairs indicates an expected call of GetTradingPairs.
func (mr *MockClientMockRecorder) GetTradingPairs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTradingPairs", reflect.TypeOf((*MockClient)(nil).GetTradingPairs), ctx)
}
