// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package client

type Payments struct {
	V1 *V1
	V3 *V3

	sdkConfiguration sdkConfiguration
}

func newPayments(sdkConfig sdkConfiguration) *Payments {
	return &Payments{
		sdkConfiguration: sdkConfig,
		V1:               newV1(sdkConfig),
		V3:               newV3(sdkConfig),
	}
}
