---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceName }}-cluster-service-account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      serviceAccountName: {{ .Values.serviceName }}-cluster-service-account
      containers:
        - image: "{{ .Values.awsAccountId }}.{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: {{ .Values.serviceName }}
          imagePullPolicy: Always
          env:
            - name: DEBUG
              value: "true"
            - name: AUTH_URI
              value: {{ .Values.global.auth }}
          ports:
            - containerPort: 8080
              name: {{ .Values.serviceName }}
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi