{{- if .Values.resource.hpa }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.serviceName }}
  annotations:
    name: {{ .Values.serviceName }}
spec:
  minReplicas: {{ .Values.hpaMinReplicas }}
  maxReplicas: {{ .Values.hpaMaxReplicas }}
  scaleTargetRef:
    kind: Deployment
    name: {{ .Values.serviceName }}
    apiVersion: apps/v1
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 60
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60
{{- end }}
