apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
spec:
  ports:
    - name: {{ .Values.serviceName }}
      port: 80
      targetPort: 8080
  selector:
    app: {{ .Values.serviceName }}
