name: Default
on:
  merge_group:
  push:
    branches:
      - main
      - releases/*
  pull_request:
    types: [ assigned, opened, synchronize, reopened, labeled ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  PR:
    if: github.event_name == 'pull_request'
    name: Check PR Title
    runs-on: "shipfox-4vcpu-ubuntu-2404"
    permissions:
      statuses: write
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Dirty:
    runs-on: "shipfox-4vcpu-ubuntu-2404"
    steps:
      - uses: 'actions/checkout@v6'
        with:
          fetch-depth: 0
      - name: Setup Env
        uses: ./.github/actions/default
        with:
          token: ${{ secrets.NUMARY_GITHUB_TOKEN }}
      - run: >
          nix --extra-experimental-features "nix-command" --extra-experimental-features "flakes"
          develop --impure --command just pre-commit
        env:
          SPEAKEASY_API_KEY: ${{ secrets.SPEAKEASY_API_KEY }}
      - name: Get changed files
        id: changed-files
        shell: bash
        run: |
          hasChanged=$(git status --porcelain)
          if (( $(echo ${#hasChanged}) != 0 )); then
            git status
            echo "There are changes in the repository"
            exit 1
          fi

  Tests:
    runs-on: "shipfox-4vcpu-ubuntu-2404"
    needs:
      - Dirty
    steps:
      - uses: 'actions/checkout@v6'
        with:
          fetch-depth: 0
      - name: Setup Env
        uses: ./.github/actions/default
        with:
          token: ${{ secrets.NUMARY_GITHUB_TOKEN }}
      - run: >
          nix --extra-experimental-features "nix-command" --extra-experimental-features "flakes"
          develop --impure --command just tests
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v6.0.0
        with:
          files: ./coverage.txt
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  GoReleaser:
    runs-on: "shipfox-4vcpu-ubuntu-2404"
    if: contains(github.event.pull_request.labels.*.name, 'build-images') || contains(github.event.pull_request.labels.*.name, 'deploy-staging') || github.ref == 'refs/heads/main' || github.event_name == 'merge_group'
    needs:
      - Dirty
    steps:
      - uses: 'actions/checkout@v6'
        with:
          fetch-depth: 0
      - name: Setup Env
        uses: ./.github/actions/default
        with:
          token: ${{ secrets.NUMARY_GITHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: "NumaryBot"
          password: ${{ secrets.NUMARY_GITHUB_TOKEN }}
      - run: >
          nix --extra-experimental-features "nix-command" --extra-experimental-features "flakes" 
          develop --impure --command just release-ci
        env:
          GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}
          SPEAKEASY_API_KEY: ${{ secrets.SPEAKEASY_API_KEY }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

  Deploy:
    runs-on: "ubuntu-24.04"
    if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'deploy-staging')
    timeout-minutes: 5
    environment: staging
    permissions:
      id-token: write
      contents: read
    needs:
      - GoReleaser
      - Tests
    steps:
      - uses: 'actions/checkout@v6'
        with:
          fetch-depth: 0
      - name: Setup Env
        uses: ./.github/actions/default
        with:
          token: ${{ secrets.NUMARY_GITHUB_TOKEN }}
      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OIDC_OAUTH_CLIENT_ID }}
          audience: ${{ secrets.TS_OIDC_AUDIENCE }}
          tags: ${{ vars.TS_TAGS }}
          version: ${{ vars.TS_VERSION }}
          args: ${{ vars.TS_ARGS }}
          retry: ${{ vars.TS_RETRY }}
          timeout: ${{ vars.TS_TIMEOUT }}
          ping: ${{ vars.TS_PING }}
      - name: "Deploy in staging"
        env:
          ARGO_AUTH_TOKEN: ${{ secrets.ARGOCD_REGION_AUTH_TOKEN }}
          SERVER: argocd.internal.formance.cloud
          APPLICATION: staging-eu-west-1-hosting-regions
          COMPONENT: payments
          TAG: ${{ github.sha }}
        run: >
          nix --extra-experimental-features "nix-command" --extra-experimental-features "flakes"
          develop --impure --command just deploy $SERVER $ARGO_AUTH_TOKEN $APPLICATION "--parameter versions.files.default.$COMPONENT=$TAG"
