name: Pull Request - Open
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  pr-style:
    uses: formancehq/gh-workflows/.github/workflows/pr-style.yml@main

  lint:
    uses: formancehq/gh-workflows/.github/workflows/golang-lint.yml@main

  test:
    uses: formancehq/gh-workflows/.github/workflows/golang-test.yml@main

  build:
    uses: formancehq/gh-workflows/.github/workflows/goreleaser-build.yml@main
    needs:
      - pr-style
      - lint
      - test
