name: Pull Request - Open
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  Test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: get deps
        run: go mod download
      - name: run tests
        run: go test -v -coverpkg=./... -coverprofile=coverage.out -covermode=atomic -tags json1 ./...
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
  Lint:
      name: 'Lint'
      runs-on: ubuntu-latest
      steps:
        - uses: actions/setup-go@v2
          with:
            go-version: '1.18'
        - uses: actions/checkout@v2
        - uses: actions/cache@v2
          with:
            path: |
              ~/.cache/go-build
              ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-go-
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            version: latest
  Build:
    name: 'Build'
    needs:
      - Test
      - Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --parallelism 4 --rm-dist --skip-validate --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: build-${{matrix.file}}
          path: ./build/**
