name: Pull Request - Open
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  Pr:
    uses: numary/gh-workflows/.github/workflows/pr-style.yml@main

  Test:
    uses: numary/gh-workflows/.github/workflows/golang-test.yml@main
    with:
      go_version: 1.18

  Lint:
    uses: numary/gh-workflows/.github/workflows/golang-lint.yml@main
    with:
      go_version: 1.18

  Build:
    name: 'Build'
    needs:
      - Test
      - Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --parallelism 4 --rm-dist --skip-validate --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}