name: Pull Request - Open
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  Pr:
    uses: numary/gh-workflows/.github/workflows/pr-style.yml@main

  Test:
    uses: numary/gh-workflows/.github/workflows/golang-test.yml@main
    with:
      go_version: 1.18

  Lint:
    uses: numary/gh-workflows/.github/workflows/golang-lint.yml@main
    with:
      go_version: 1.18

  Build:
    uses: numary/gh-workflows/.github/workflows/goreleaser-build.yml@main
    needs:
      - Test