on:
  push:
    branches-ignore:
      - main

name: Push
jobs:
  Build:
    uses: numary/gh-workflows/.github/workflows/docker-build.yml@main
    with:
      go_version: 1.17
      service: payments
      version: develop
      sha: ${{ github.sha }}
      env: staging
    secrets:
      NUMARY_GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}