name: release
on:
  release:
    types: [prereleased, released]
permissions:
  contents: write
jobs:
  lint:
    uses: numary/gh-workflows/.github/workflows/golang-lint.yml@main

  test:
    uses: numary/gh-workflows/.github/workflows/golang-test.yml@main

  build:
    uses: numary/gh-workflows/.github/workflows/goreleaser-release.yml@main
    secrets:
      NUMARY_GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}
      FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
    needs:
      - lint
      - test

  build-docker:
    name: 'Build & Publish Docker'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: "NumaryBot"
          password: ${{ secrets.NUMARY_GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/numary/payments:latest,ghcr.io/numary/payments:${{ github.event.release.tag_name }}
          build-args: |
            APP_SHA=${{ github.sha }}
            VERSION=${{ github.event.release.tag_name }}
