name: release
on:
  release:
    types: [prereleased, released]

jobs:
  Build:
    uses: numary/gh-workflows/.github/workflows/docker-build.yml@main
    with:
      go_version: 1.17
      service: payments
      version: develop
      sha: ${{ github.sha }}
      env: prod
    secrets:
      NUMARY_GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}

  Deploy:
    needs:
      - Build
    uses: numary/gh-workflows/.github/workflows/deploy-production.yml@main
    with:
      service: payments
      version: payments-${{ github.sha }}
    secrets:
      ARGOCD_TOKEN: ${{ secrets.ARGOCD_PRODUCTION }}